package com.kevin.dueltime4.yaml.message;

public enum Msg {
    LANGUAGE_NAME("LanguageName", "&c繁體中文(系統內建)"),
    STRING_NONE("String.none", "無"),
    STRING_TRUE("String.true", "是"),
    STRING_FALSE("String.false", "否"),
    STRING_LIST("String.list", "{line}行列表：{brief_content}",
            "line", "brief_content"),
    STRING_WIN("String.win", "&a勝利"),
    STRING_LOSE("String.lose", "&7失敗"),
    STRING_DRAW("String.draw", "&6平局"),
    STRING_GAMES("String.games", "場"),
    STRING_SECOND("String.seconds", "秒"),
    STRING_NO_RANK("String.no-rank", "&7無排名"),
    STRING_COMMAND_EXECUTOR_PLAYER("String.command-executor.player", "玩家"),
    STRING_COMMAND_EXECUTOR_OP("String.command-executor.op", "管理員"),
    STRING_COMMAND_EXECUTOR_CONSOLE("String.command-executor.console", "後臺"),
    EXCEPTION_ARENA_INITIALIZE_FAIL_INVALID_ARENA_TYPE("Exception.arena.initialize-fail-invalid-arena-type", "競技場 {arena_name}(ID:{arena_id}) 初始化失敗，不存在ID為 '{arena_id}' 的競技場型別，請檢查是否缺少相關附屬外掛",
            "arena_id", "arena_name", "type_id"),
    LEVEL_LEVEL_UP_MESSAGE("Level.level-up-message", "&a恭喜你的DT等級升到了 &b{level} &a級",
            "level"),
    LEVEL_TIER_UP_MESSAGE("Level.tier-up-message", "&b恭喜你的DT段位升到了 &f{tier}",
            "tier"),
    LEVEL_TIER_UP_BROADCAST("Level.tier-up-broadcast", "&a[恭喜] &b玩家 &3{player} &b的段位升到了 &f{tier}",
            "player", "tier"),
    LEVEL_TIER_DOWN_MESSAGE("Level.tier-down-message", "&c你的DT段位掉到了 &f{tier}",
            "tier"),
    ARENA_WAIT_START("Arena.wait.start", "&7已加入競技場 &b{arena}&7 的等待佇列...",
            "arena"),
    ARENA_WAIT_SWITCH("Arena.wait.switch", "&7已切換至競技場 &b{arena}&7 的等待佇列...",
            "arena"),
    ARENA_WAIT_STOP("Arena.wait.stop", "&7取消等待競技場：&b{arena}",
            "arena"),
    ARENA_WAIT_ACTION_BAR_SEARCHING("Arena.wait.action-bar-searching", "&7正在為你尋找對手... &f{s}&7 秒 &8| &7等待中：&b{count}&7 人",
            "s", "count"),
    ARENA_PROTECTION_WALK_IN_WHILE_AVAILABLE("Arena.protection.walk-in-while-available", "&c&l[!]&c無賽事時，你不能進入競技場 &e{name}&c 的場地"
            , "name"),
    ARENA_PROTECTION_WALK_IN_WHILE_IN_PROGRESS("Arena.protection.walk-in-while-in-progress", "&c&l[!]&c競技場 &e{name}&c 正在比賽，請不要進入"
            , "name"),
    ARENA_PROTECTION_TELEPORT_TO_WHILE_AVAILABLE("Arena.protection.teleport-to-while-available", "&c&l[!]&c無賽事時，你不能傳送到競技場 &e{name}&c 的場地"
            , "name"),
    ARENA_PROTECTION_TELEPORT_TO_WHILE_IN_PROGRESS("Arena.protection.teleport-to-while-in-progress", "&c&l[!]&c競技場 &e{name}&c 正在比賽，請不要傳送過去"
            , "name"),
    ARENA_PROTECTION_ATTACK_GAMER("Arena.protection.attack-gamer", "&c&l[!]&c請不要干擾競技場 &e{name}&c 上的參與玩家"
            , "name"),
    ARENA_PROTECTION_BREAK("Arena.protection.break", "&c&l[!]&c你不能破壞競技場 &e{name}&c 內的方塊"
            , "name"),
    ARENA_PROTECTION_PLACE("Arena.protection.place", "&c&l[!]&c你不能在競技場 &e{name}&c 內放置方塊"
            , "name"),
    ARENA_PROTECTION_PLACE_OVER("Arena.protection.place-over", "&c&l[!]&c你不能在競技場 &e{name}&c 上空放置方塊"
            , "name"),
    ARENA_PROTECTION_INTERACT("Arena.protection.interact", "&c&l[!]&c你不能與競技場 &e{name}&c 內的方塊互動"
            , "name"),
    ARENA_PROTECTION_POUR_LIQUID("Arena.protection.pour-liquid", "&c&l[!]&c你不能在競技場 &e{name}&c 內傾倒液體"
            , "name"),
    ARENA_PROTECTION_GET_LIQUID("Arena.protection.get-liquid", "&c&l[!]&c你不能撈取競技場 &e{name}&c 內的液體"
            , "name"),
    ARENA_TYPE_CLASSIC_NAME("Arena.type.classic.name", "經典"),
    ARENA_TYPE_CLASSIC_START_TITLE("Arena.type.classic.start.title", "&a&l比賽開始"),
    ARENA_TYPE_CLASSIC_START_SUBTITLE("Arena.type.classic.start.subtitle", "&f亮劍吧！"),
    ARENA_TYPE_CLASSIC_END_RESULT_STOPPED("Arena.type.classic.end.result-stopped", "&c&l[!]&c本場比賽被系統或管理員強制結束！將不會產生任何記錄"),
    ARENA_TYPE_CLASSIC_END_RESULT_STOPPED_WITH_REASON("Arena.type.classic.end.result-stopped-with-reason", "&c&l[!]&c本場比賽被系統或管理員強制結束！將不會產生任何記錄。強制結束原因：&f{reason}",
            "reason"),
    ARENA_TYPE_CLASSIC_END_RESULT_WIN("Arena.type.classic.end.result-win", "&2&l[!]&a你取得了本場經典模式下比賽的勝利"),
    ARENA_TYPE_CLASSIC_END_RESULT_LOSE("Arena.type.classic.end.result-lose", "&6&l[!]&c你在本場經典模式下的比賽中落敗"),
    ARENA_TYPE_CLASSIC_END_RESULT_DRAW("Arena.type.classic.end.result-draw", "&b&l[!]&3本場經典模式下的比賽以平局結束"),
    ARENA_TYPE_CLASSIC_END_NOTIFY_INFO("Arena.type.classic.end.notify-info", new String[]{
            "&7&m───&f&l&m────────────────────────&7&m───",
            "    &b場地: &f{arena}",
            "    &b對手: &f{player}&7(&f{level_display_name}&7)",
            "    &b歷時: &3{time}秒",
            "    &b經驗: &f{exp_change}",
            "    &b更多資料：&7[clickable]more_data::&7(滑鼠懸停此處檢視)::&b總計傷害:&3{total_damage}||&b最大傷害:&3{max_damage}||&b平均傷害:&3{average_damage}[clickable]",
            "&7&m───&f&l&m────────────────────────&7&m───",
    },
            new String[][]{{"more_data", "", "", ""}},
            "arena", "player", "level_display_name", "time", "exp_change", "total_damage", "max_damage", "average_damage"),
    ARENA_TYPE_CLASSIC_EARN_POINT("Arena.earn-point", "&a恭喜你因贏得比賽獲得了 &d{point} &a點積分，當前積分：&a{point_now}"
            , "point", "point_now"),
    ARENA_TYPE_CLASSIC_END_BROADCAST("Arena.type.classic.end.broadcast", "&3[戰報] &b玩家 &d{winner} &b在經典模式競技場 &e{arena}&b 上以 &a{time} &b秒的時間擊敗了對手 &e{loser} &b！",
            "arena", "winner", "loser", "time"),
    ARENA_TYPE_CLASSIC_END_BROADCAST_DRAW("Arena.type.classic.end.broadcast-draw", "&3[戰報] 玩家 &d{player1} &b和 &d{player2} &b在經典模式競技場 &e{arena}&b 上打成平手！歷時 &a{time} &b秒",
            "arena", "player1", "player2", "time"),
    ARENA_TYPE_CLASSIC_DAMAGE_DURING_COUNTDOWN("Arena.type.classic.damage-during-countdown", "&7比賽還未還沒正式開始，不可發起攻擊"),
    ARENA_TYPE_CLASSIC_USE_COMMAND_IN_GAME("Arena.type.classic.use-command-in-game", "&c比賽過程中禁止使用這個指令"),
    ARENA_TYPE_CLASSIC_QUIT_INFORM_OPPONENT("Arena.type.classic.quit-inform-opponent", "&d你的對手主動退出了比賽！"),
    ARENA_TYPE_CLASSIC_LEAVE_SERVER_INFORM_OPPONENT("Arena.type.classic.leave-server-inform-opponent", "&d你的對手離開了伺服器！"),
    ARENA_TYPE_CLASSIC_WIN_TITLE("Arena.type.classic.win-title", "&a&l贏"),
    ARENA_TYPE_CLASSIC_WIN_SUBTITLE("Arena.type.classic.win-subtitle", "&f恭喜你贏得了這場比賽！"),
    ARENA_TYPE_CLASSIC_DELAYED_BACK_GAMER_TITLE("Arena.type.classic.delayed-back.gamer-title", "&b&l{countdown}",
            "countdown"),
    ARENA_TYPE_CLASSIC_DELAYED_BACK_GAMER_SUBTITLE("Arena.type.classic.delayed-back.gamer-subtitle", "&7即將傳送離開競技場..."),
    ARENA_TYPE_CLASSIC_DELAYED_BACK_SPECTATOR_TITLE("Arena.type.classic.delayed-back.spectator-title", "&b&l{countdown}",
            "countdown"),
    ARENA_TYPE_CLASSIC_DELAYED_BACK_SPECTATOR_SUBTITLE("Arena.type.classic.delayed-back.spectator-subtitle", "&7即將傳送離開觀眾席..."),
    ARENA_TYPE_CLASSIC_FUNCTION_TIME_LIMIT_NAME("Arena.type.classic.function.time-limit.name", "比賽限時"),
    ARENA_TYPE_CLASSIC_FUNCTION_TIME_LIMIT_DESCRIPTION("Arena.type.classic.function.time-limit.description", "為比賽設定限定時間(單位為秒)，若超出限時則根據預設方案判定輸贏或平局，需要傳入整數型資料"),
    ARENA_TYPE_CLASSIC_FUNCTION_TIME_LIMIT_BOSSBAR_TITLE("Arena.type.classic.function.time-limit.bossbar-title", "&f比賽剩餘 &3{time} &f秒",
            "time"),
    ARENA_TYPE_CLASSIC_FUNCTION_COUNTDOWN_NAME("Arena.type.classic.function.countdown.name", "開始前倒計時"),
    ARENA_TYPE_CLASSIC_FUNCTION_COUNTDOWN_DESCRIPTION("Arena.type.classic.function.countdown.description", "為比賽設定開始前倒計時(單位為秒)，需要傳入一個整數型資料表示秒數、傳入一個布林值表示是否允許倒計時期間玩家移動"),
    ARENA_TYPE_CLASSIC_FUNCTION_COUNTDOWN_GAME_TITLE("Arena.type.classic.function.time-limit.game-title", "&b&l{time}",
            "time"),
    ARENA_TYPE_CLASSIC_FUNCTION_COUNTDOWN_GAME_SUBTITLE("Arena.type.classic.function.time-limit.game-subtitle", "&f比賽即將開始...",
            "time"),
    ARENA_TYPE_CLASSIC_FUNCTION_INVENTORY_CHECK_KEYWORD_NAME("Arena.type.classic.function.check-inventory-keyword.name", "入場前揹包檢查(依關鍵詞)"),
    ARENA_TYPE_CLASSIC_FUNCTION_INVENTORY_CHECK_KEYWORD_DESCRIPTION("Arena.type.classic.function.inventory-check-keyword.description", "禁用某些特殊的物品入場，檢測揹包中是否裝有名稱或lore中含有某些關鍵詞的物品，如果有則制止開賽"),
    ARENA_TYPE_CLASSIC_FUNCTION_INVENTORY_CHECK_KEYWORD_DETECTED_TIP("Arena.type.classic.function.inventory-check-keyword.detected-tip", "&c&l[!] &c在你的揹包中檢測到競技場 &e{arena_name}&c 所禁用的特殊物品： [clickable]item::&f[{item_name}]&7(點選檢視詳情)::{item_lore}[clickable]",
            new String[][]{{"item", "/dueltime click item", "", ""}},
            "arena_name", "item_name", "item_lore"),
    ARENA_TYPE_CLASSIC_FUNCTION_INVENTORY_CHECK_KEYWORD_DETECTED("Arena.type.classic.function.inventory-check-keyword.detected", "&c玩家 &e{player}&c 揹包裡攜帶有競技場 &e{arena_name}&c 所禁用的特殊物品，已通知該玩家相關細節，請再次確保雙方都沒有攜帶其他禁用的特殊物品後再重新發起比賽",
            "player", "arena_name"),
    ARENA_TYPE_CLASSIC_FUNCTION_INVENTORY_CHECK_TYPE_NAME("Arena.type.classic.function.inventory-check-type.name", "入場前揹包檢查(依物品種類)"),
    ARENA_TYPE_CLASSIC_FUNCTION_INVENTORY_CHECK_TYPE_DESCRIPTION("Arena.type.classic.function.inventory-check-type.description", "為比賽設定揹包攜帶物品限制，檢測揹包中是否裝有某個特定種類的物品，如果有則制止開賽"),
    ARENA_TYPE_CLASSIC_FUNCTION_INVENTORY_CHECK_TYPE_DETECTED_TIP("Arena.type.classic.function.inventory-check-type.detected-tip", "&c&l[!] &c在你的揹包中檢測到競技場 &e{arena_name}&c 所禁用的特定種類物品： [clickable]item::&f[{item_name}]&7(點選檢視詳情)::{item_lore}[clickable]",
            new String[][]{{"item", "/dueltime click item", "", ""}},
            "arena_name", "item_name", "item_lore"),
    ARENA_TYPE_CLASSIC_FUNCTION_INVENTORY_CHECK_TYPE_DETECTED("Arena.type.classic.function.inventory-check-type.detected", "&c玩家 &e{player}&c 揹包裡攜帶有競技場 &e{arena_name}&c 所禁用的特定種類物品，已通知該玩家相關細節，請再次確保雙方都沒有攜帶其他禁用種類的物品後再重新發起比賽",
            "player", "arena_name"),

    ARENA_TYPE_CLASSIC_FUNCTION_PRE_GAME_COMMAND_NAME("Arena.type.classic.function.pre-game-command.name", "賽前執行指令組"),
    ARENA_TYPE_CLASSIC_FUNCTION_PRE_GAME_COMMAND_DESCRIPTION("Arena.type.classic.function.pre-game-command.description", "為比賽設定玩家賽前剛入場時執行的指令組，支援分別以不同的身份執行"),
    ARENA_TYPE_CLASSIC_FUNCTION_SPECTATE_NAME("Arena.type.classic.function.spectate.name", "觀戰"),
    ARENA_TYPE_CLASSIC_FUNCTION_SPECTATE_DESCRIPTION("Arena.type.classic.function.spectate.description", "為比賽設定觀戰區域，使得玩家可與透過/dueltime spectate指令來觀看某個經典模式競技場的比賽"),
    ARENA_TYPE_CLASSIC_FUNCTION_BAN_ENTITY_SPAWN_NAME("Arena.type.classic.function.ban-entity-spawn.name", "禁止實體生成(包括自然的與人為的)"),
    ARENA_TYPE_CLASSIC_FUNCTION_BAN_ENTITY_SPAWN_DESCRIPTION("Arena.type.classic.function.ban-entity-spawn.description", "禁止實體刷出(包括自然的與人為的)，可以設定白名單"),
    ARENA_TYPE_CLASSIC_FUNCTION_SPECTATE_GAMER_HEALTH_BOSSBAR("Arena.type.classic.function.spectate.gamer-health-bossbar", "&f選手 &b{player}&f 的實時血量：&a{health}&2/{max_health}",
            "player", "health", "max_health"),
    ARENA_TYPE_CLASSIC_FUNCTION_SPECTATE_FAIL_UNAVAILABLE("Arena.type.classic.function.spectate.fail-unavailable", "&c管理員尚未給競技場 &e{arena} &c開啟觀戰功能",
            "arena"),
    ARENA_TYPE_CLASSIC_FUNCTION_SPECTATE_SUCCESSFULLY("Arena.type.classic.function.spectate.successfully", "&a已將你帶到競技場 &b{arena} &a的觀戰區域！",
            "arena"),
    ARENA_TYPE_CLASSIC_FUNCTION_STOP_SPECTATE_SUCCESSFULLY("Arena.type.classic.function.spectate.stop-successfully", "&a你結束了對競技場 &b{arena} &a的觀看",
            "arena"),
    ARENA_TYPE_CLASSIC_FUNCTION_SPECTATE_OVER("Arena.type.classic.function.spectate.over", new String[]{
            "&a你觀看的比賽結束！詳情如下：",
            "&7&m───&f&l&m────────────────────────&7&m───",
            "    &b場地: &f{arena}",
            "    &b選手: &3{gamers}",
            "    &b獲勝: &d{winner}",
            "    &b歷時: &3{time}秒",
            "&7&m───&f&l&m────────────────────────&7&m───",
    },
            "arena", "gamers", "winner", "time"),
    ARENA_TYPE_CLASSIC_FUNCTION_SPECTATE_OVER_IN_A_DRAW("Arena.type.classic.function.spectate.over-in-a-draw", new String[]{
            "&a你觀看的比賽以平局結束，詳情如下：",
            "&7&m───&f&l&m────────────────────────&7&m───",
            "    &b場地: &f{arena}",
            "    &b選手: &3{gamers}",
            "    &b歷時: &3{time}秒",
            "&7&m───&f&l&m────────────────────────&7&m───",
    },
            "arena", "gamers", "time"),
    ARENA_TYPE_CLASSIC_FUNCTION_SPECTATE_OVER_BY_STOP("Arena.type.classic.function.spectate.over-by-stop", "&c競技場 &e{arena}&c 上的比賽被管理員強制結束！",
            "arena"),
    ARENA_TYPE_CLASSIC_FUNCTION_SPECTATE_SPECTATOR_MOVE_OUT_ZONE("Arena.type.classic.function.spectate.spectator-move-out-zone", "&c請不要離開觀賽區域，如果要結束觀賽，請再次輸入觀賽指令"),
    RECORD_TYPE_CLASSIC_TITLE("Record.type.classic.title", "&f經典模式比賽記錄"),
    RECORD_TYPE_CLASSIC_CONTENT_ARENA_NAME("Record.type.classic.content.arena-name", "&b場地: &f{arena_name}",
            "arena_name"),
    RECORD_TYPE_CLASSIC_CONTENT_RESULT("Record.type.classic.content.result", "&b結果: &f{result}",
            "result"),
    RECORD_TYPE_CLASSIC_CONTENT_OPPONENT("Record.type.classic.content.opponent", "&b對手: &e{opponent}",
            "opponent"),
    RECORD_TYPE_CLASSIC_CONTENT_TIME("Record.type.classic.content.time", "&b用時: &e{time}秒",
            "time"),
    RECORD_TYPE_CLASSIC_CONTENT_EXP_CHANGE("Record.type.classic.content.exp-change", "&b經驗變化: &f{exp_change}",
            "exp_change"),
    RECORD_TYPE_CLASSIC_CONTENT_TOTAL_DAMAGE("Record.type.classic.content.total-damage", "&b總計傷害: &e{total_damage}點",
            "total_damage"),
    RECORD_TYPE_CLASSIC_CONTENT_MAX_DAMAGE("Record.type.classic.content.max-damage", "&b最大傷害: &e{max_damage}點",
            "max_damage"),
    RECORD_TYPE_CLASSIC_CONTENT_AVERAGE_DAMAGE("Record.type.classic.content.average-damage", "&b平均傷害: &e{average_damage}點",
            "average_damage"),
    RECORD_TYPE_CLASSIC_CONTENT_DATE("Record.type.classic.content.date", "&b比賽日期: &e{date}",
            "date"),
    ERROR_NO_PERMISSION("Error.no-permission", "&c你沒有許可權這麼做！"),
    ERROR_NOT_PLAYER_EXECUTOR("Error.not-player-executor", "&c只有玩家能執行這個指令！"),
    ERROR_SUB_COMMAND_NOT_EXISTS("Error.sub-command-not-exists", "&c子指令 &e'{enter}' &c不存在，請檢查輸入",
            "enter"),
    ERROR_INCORRECT_NUMBER_FORMAT("Error.incorrect-number-format", "&e'{enter}' &c不是數字，請注意格式",
            "enter"),
    ERROR_INCORRECT_INTEGER_FORMAT("Error.incorrect-integer-format", "&e'{enter}' &c不是整數，請注意格式",
            "enter"),
    ERROR_INCORRECT_ID_FORMAT("Error.incorrect-id-format", "&e'{enter}' &c不符合ID命名規範，ID只能包含英文字母、數字和下劃線",
            "enter"),
    ERROR_VALUE_IS_NOT_POSITIVE("Error.value-is-not-positive", "&c請輸入一個有效的正數！你所輸入的 &e'{enter}' &c不符合條件",
            "enter"),
    ERROR_VALUE_IS_NEGATIVE("Error.value-is-negative", "&c請輸入一個非負數！你所輸入的 &e'{enter}' &c不符合條件",
            "enter"),
    ERROR_INCORRECT_BOOLEAN("Error.incorrect-boolean-format", "&c請輸入字母'T'或'F'，分別表示[是]和[否]'"),
    ERROR_PLAYER_NO_FOUND("Error.player-no-found", "&c名為 &e'{player}' &c的玩家可能不存在",
            "player"),
    ERROR_INCORRECT_STRING_INTEGER_PAIR_FORMAT("Error.incorrect-string-integer-pair-format", "&c請輸入 &e文字:數字 &c來表示字串-整數對，例如 &e'example:3'"),
    ERROR_INCORRECT_STRING_INTEGER_PAIR_FORMAT_INTEGER("Error.incorrect-string-integer-pair-format-integer", "&c分割符 &e':' &c後面應該為一個整數"),
    ERROR_INCORRECT_EXECUTOR_COMMAND_PAIR_FORMAT("Error.incorrect-executor-command-pair-format", "&c請輸入 &e執行身份:指令內容 &c，例如 &e'console:fly {player}'"),
    PROGRESS_REPEATEDLY_JOIN("Progress.repeatedly-join", "&c你已經在過程 &e{progress} &c中了",
            "progress"),
    PROGRESS_JOIN_WHILE_HANDLING_OTHER("Progress.join-while-handling-other", "&c請先完成或退出過程 &e{progress}",
            "progress"),
    PROGRESS_JOIN_SUCCESSFULLY("Progress.join-successfully", "&a你已進入過程 &b{progress} &a中，請按照後續提示逐步操作。&7(在此期間你可以根據需要輸入&f-r&7回退步驟，輸入&f-p&7暫停過程，輸入&f-c&7繼續過程，輸入&f-e&7退出過程)",
            "progress"),
    PROGRESS_BOSSBAR_TIP("Progress.boss-bar-tip", "&a{name}({now}/{total}): {tip}",
            "name", "now", "total", "tip"),
    PROGRESS_BOSSBAR_FREE_TIP("Progress.boss-bar-free-tip", new String[]{
            "",
            "&d{progress}&f:",
            "&b進度&f:&3{now}/{total} &f[{progress_bar_progress_20_|_a_7}&f]",
            "&b提示&f:&f{tip}",
            ""},
            "progress", "now", "total", "progress_bar_progress", "tip"),
    PROGRESS_BOSSBAR_MESSAGE_FINISH_STRING("Progress.boss-bar-message-finish-string", "&a&l大功告成"),
    PROGRESS_AUTO_UPLOAD_LOCATION_DIFFERENT_WORLD("Progress.auto-upload.location-different-world", "&c你所選的位置點必須與上一個位置位於同一個世界！"),
    PROGRESS_AUTO_UPLOAD_LOCATION_THE_SAME_BLOCK("Progress.auto-upload.location-the-same-block", "&c你所選的點不能和上一個點位於同一個方塊"),
    PROGRESS_AUTO_UPLOAD_LOCATION_OVERLAY_WITH_OTHER_ARENA("Progress.auto-upload.location-overlay-with-other-arena", "&c當前選點和上一個選點所構成的三維空間與競技場 &e{arena} &c的三維空間交疊！請換一個點",
            "arena"),
    PROGRESS_FINISH_MESSAGE("Progress.finish.message", "&f你完成了過程：§a{progress}",
            "progress"),
    PROGRESS_FINISH_TITLE("Progress.finish.title", "&b✦"),
    PROGRESS_FINISH_SUBTITLE("Progress.finish.subtitle", "&f已完成過程：§a{progress}",
            "progress"),
    PROGRESS_OPERATION_REVERSE_TITLE("Progress.operation.reverse.title", "&6↺"),
    PROGRESS_OPERATION_REVERSE_SUBTITLE("Progress.operation.reverse.subtitle", "&7步驟回退"),
    PROGRESS_OPERATION_REVERSE_THE_FIRST_STEP("Progress.operation.reverse.the-first-step", "&c已經是第一步了，無法回退"),
    PROGRESS_OPERATION_PAUSE_TITLE("Progress.operation.pause.title", "&e┃┃"),
    PROGRESS_OPERATION_PAUSE_SUBTITLE("Progress.operation.pause.subtitle", "&7暫停步驟操作"),
    PROGRESS_OPERATION_PAUSE_HAS_BEEN_PAUSED("Progress.operation.pause.has-been-paused", "&c已經處於暫停狀態"),
    PROGRESS_OPERATION_CONTINUE_TITLE("Progress.operation.continue.title", "&a▶"),
    PROGRESS_OPERATION_CONTINUE_SUBTITLE("Progress.operation.continue.subtitle", "&7恢復步驟操作"),
    PROGRESS_OPERATION_CONTINUE_HAS_BEEN_PAUSED("Progress.operation.continue.has-been-paused", "&c已經處於正常操作狀態"),
    PROGRESS_OPERATION_EXIT_SUCCESSFULLY("Progress.operation.exit.successfully", "&7已退出過程：§a{progress}",
            "progress"),
    PROGRESS_OPERATION_LIST_ENTER_TITLE("Progress.operation.list.enter.title", "&f[&bT&f]"),
    PROGRESS_OPERATION_LIST_ENTER_SUBTITLE("Progress.operation.list.enter.subtitle", "&7已新增一行，當前列表：&f{brief_content}",
            "brief_content"),
    PROGRESS_OPERATION_LIST_INCORRECT_DATA_TYPE("Progress.operation.list.incorrect-data-type", "&c現在上傳的資料型別不是列表，不能使用這個運算子"),
    PROGRESS_OPERATION_LIST_EMPTY_DATA("Progress.operation.list.empty-data", "&c請先輸入一些內容"),
    PROGRESS_TYPE_UPLOAD_DATA_FOR_ARENA_FUNCTION("Progress.type.upload-data-for-arena-function", "上傳附加功能所需要資料"),
    PROGRESS_TYPE_CREATE_CLASSIC_ARENA_NAME("Progress.type.create-classic-arena.name", "建立經典型別競技場"),
    PROGRESS_TYPE_CREATE_CLASSIC_ARENA_STEP_1_TIP("Progress.type.create-classic-arena.step.1.tip", "左鍵點選方塊以選擇A點"),
    PROGRESS_TYPE_CREATE_CLASSIC_ARENA_STEP_1_TITLE("Progress.type.create-classic-arena.step.1.title", "&a✔"),
    PROGRESS_TYPE_CREATE_CLASSIC_ARENA_STEP_1_SUBTITLE("Progress.type.create-classic-arena.step.1.subtitle", "&f成功選擇A點 座標&e{}"),
    PROGRESS_TYPE_CREATE_CLASSIC_ARENA_STEP_2_TIP("Progress.type.create-classic-arena.step.2.tip", "左鍵點選方塊以選擇B點"),
    PROGRESS_TYPE_CREATE_CLASSIC_ARENA_STEP_2_TITLE("Progress.type.create-classic-arena.step.2.title", "&a✔"),
    PROGRESS_TYPE_CREATE_CLASSIC_ARENA_STEP_2_SUBTITLE("Progress.type.create-classic-arena.step.2.subtitle", "&f成功選擇B點 座標&e{}"),
    PROGRESS_TYPE_CREATE_CLASSIC_ARENA_STEP_3_TIP("Progress.type.create-classic-arena.step.3.tip", "點選螢幕使當前位置作為玩家1的出生點"),
    PROGRESS_TYPE_CREATE_CLASSIC_ARENA_STEP_3_TITLE("Progress.type.create-classic-arena.step.3.title", "&a✔"),
    PROGRESS_TYPE_CREATE_CLASSIC_ARENA_STEP_3_SUBTITLE("Progress.type.create-classic-arena.step.3.subtitle", "&f成功選擇出生點1 座標&e{}"),
    PROGRESS_TYPE_CREATE_CLASSIC_ARENA_STEP_4_TIP("Progress.type.create-classic-arena.step.4.tip", "點選螢幕使當前位置作為玩家2的出生點"),
    PROGRESS_TYPE_CREATE_CLASSIC_ARENA_STEP_4_TITLE("Progress.type.create-classic-arena.step.4.title", "&a✔"),
    PROGRESS_TYPE_CREATE_CLASSIC_ARENA_STEP_4_SUBTITLE("Progress.type.create-classic-arena.step.4.subtitle", "&f成功選擇出生點2 座標&e{}"),
    PROGRESS_TYPE_CREATE_CLASSIC_ARENA_STEP_5_TIP("Progress.type.create-classic-arena.step.5.tip", "輸入競技場ID (只能包含英文、數字、下劃線）"),
    PROGRESS_TYPE_CREATE_CLASSIC_ARENA_STEP_5_TITLE("Progress.type.create-classic-arena.step.5.title", "&a✔"),
    PROGRESS_TYPE_CREATE_CLASSIC_ARENA_STEP_5_SUBTITLE("Progress.type.create-classic-arena.step.5.subtitle", "&f成功設定ID &b{}"),
    PROGRESS_TYPE_CREATE_CLASSIC_ARENA_STEP_6_TIP("Progress.type.create-classic-arena.step.6.tip", "輸入競技場名稱 (支援顏色符號）"),
    PROGRESS_TYPE_CREATE_CLASSIC_ARENA_STEP_6_TITLE("Progress.type.create-classic-arena.step.6.title", "&a✔"),
    PROGRESS_TYPE_CREATE_CLASSIC_ARENA_STEP_6_SUBTITLE("Progress.type.create-classic-arena.step.6.subtitle", "&f成功設定名稱 &f{}"),
    PROGRESS_TYPE_SET_FUNCTION_TIME_LIMIT_NAME("Progress.type.set-function-time-limit.name", "增添附加功能：時間限制"),
    PROGRESS_TYPE_SET_FUNCTION_TIME_LIMIT_STEP_1_TIP("Progress.type.set-function.time-limit.step.1.tip", "輸入時間限制，單位為秒"),
    PROGRESS_TYPE_SET_FUNCTION_TIME_LIMIT_STEP_1_TITLE("Progress.type.set-function.time-limit.step.1.title", "&a✔"),
    PROGRESS_TYPE_SET_FUNCTION_TIME_LIMIT_STEP_1_SUBTITLE("Progress.type.set-function.time-limit.step.1.subtitle", "&f成功設定時間限制 &b{}秒"),
    PROGRESS_TYPE_SET_FUNCTION_COUNTDOWN_STEP_1_TIP("Progress.type.set-function.countdown.step.1.tip", "輸入倒計時秒數，單位為秒"),
    PROGRESS_TYPE_SET_FUNCTION_COUNTDOWN_STEP_1_TITLE("Progress.type.set-function.countdown.step.1.title", "&a✔"),
    PROGRESS_TYPE_SET_FUNCTION_COUNTDOWN_STEP_1_SUBTITLE("Progress.type.set-function.countdown.step.1.subtitle", "&f成功設定倒計時秒數 &b{}秒"),
    PROGRESS_TYPE_SET_FUNCTION_COUNTDOWN_STEP_2_TIP("Progress.type.set-function.countdown.step.2.tip", "輸入T或F分別表示允許或不允許倒計時期間玩家可以在競技場中移動"),
    PROGRESS_TYPE_SET_FUNCTION_COUNTDOWN_STEP_2_TITLE("Progress.type.set-function.countdown.step.2.title", "&a✔"),
    PROGRESS_TYPE_SET_FUNCTION_COUNTDOWN_STEP_2_SUBTITLE("Progress.type.set-function.countdown.step.2.subtitle", "&f成功設定倒計時期間玩家是否可以移動：{}"),
    PROGRESS_TYPE_SET_FUNCTION_INVENTORY_CHECK_KEYWORD_STEP_1_TIP("Progress.type.set-function.inventory-check-keyword.step.1.tip", "輸入檢測範圍，name表示只檢測展示名，lore表示只檢測描述，all表示都檢查"),
    PROGRESS_TYPE_SET_FUNCTION_INVENTORY_CHECK_KEYWORD_STEP_1_TITLE("Progress.type.set-function.inventory-check-keyword.step.1.title", "&a✔"),
    PROGRESS_TYPE_SET_FUNCTION_INVENTORY_CHECK_KEYWORD_STEP_1_SUBTITLE("Progress.type.set-function.inventory-check-keyword.step.1.subtitle", "&f成功指定檢測範圍 &b{}"),
    PROGRESS_TYPE_SET_FUNCTION_INVENTORY_CHECK_KEYWORD_STEP_1_INCORRECT_RANGE("Progress.type.set-function.inventory-check-keyword.step.1.incorrect-range", "&e'{enter}' &c不是一個正確的檢測範圍，提示：輸入name表示只檢測展示名，輸入lore表示只檢測描述，輸入all表示都檢查",
            "enter"),
    PROGRESS_TYPE_SET_FUNCTION_INVENTORY_CHECK_KEYWORD_STEP_2_TIP("Progress.type.set-function.inventory-check-keyword.step.2.tip", "上傳關鍵詞列表，輸入內容後傳送即新增一行，輸入-l結束並上傳整個列表"),
    PROGRESS_TYPE_SET_FUNCTION_INVENTORY_CHECK_KEYWORD_STEP_2_TITLE("Progress.type.set-function.inventory-check-keyword.step.2.title", "&a✔"),
    PROGRESS_TYPE_SET_FUNCTION_INVENTORY_CHECK_KEYWORD_STEP_2_SUBTITLE("Progress.type.set-function.inventory-check-keyword.step.2.subtitle", "&f成功上傳關鍵詞列表 &b{}"),
    PROGRESS_TYPE_SET_FUNCTION_INVENTORY_CHECK_TYPE_STEP_1_TIP("Progress.type.set-function.inventory-check-type.step.1.tip", "上傳種類資訊列表，輸入內容後傳送即新增一行，格式為Material名+冒號+子ID，輸入-l結束並上傳整個列表"),
    PROGRESS_TYPE_SET_FUNCTION_INVENTORY_CHECK_TYPE_STEP_1_TITLE("Progress.type.set-function.inventory-check-type.step.1.title", "&a✔"),
    PROGRESS_TYPE_SET_FUNCTION_INVENTORY_CHECK_TYPE_STEP_1_SUBTITLE("Progress.type.set-function.inventory-check-type.step.1.subtitle", "&f成功上傳種類資訊列表 &b{}"),
    PROGRESS_TYPE_SET_FUNCTION_PRE_GAME_COMMAND_STEP_1_TIP("Progress.type.set-function.pre-game-command.step.1.tip", "上傳指令列表，輸入內容後傳送即新增一行，格式為執行身份+冒號+內容，輸入-l結束並上傳整個列表"),
    PROGRESS_TYPE_SET_FUNCTION_PRE_GAME_COMMAND_STEP_1_TITLE("Progress.type.set-function.pre-game-command.step.1.title", "&a✔"),
    PROGRESS_TYPE_SET_FUNCTION_PRE_GAME_COMMAND_STEP_1_SUBTITLE("Progress.type.set-function.pre-game-command.step.1.subtitle", "&f成功上傳指令組 &b{}"),
    PROGRESS_TYPE_SET_FUNCTION_PRE_GAME_COMMAND_STEP_1_INCORRECT_EXECUTOR("Progress.type.set-function.pre-game-command.step.1.incorrect-executor", "&e'{enter}' &c不是一個正確的執行身份名，提示：player表示以玩家身份執行，op表示以管理員身份執行，console表示以後臺身份執行，console_single_time則表示以後臺身份執行一次，不針對任何玩家",
            "enter"),
    PROGRESS_TYPE_SET_FUNCTION_SPECTATOR_STEP_1_TIP("Progress.type.set-function.spectator.step.1.tip", "左鍵點選方塊選擇觀戰區域A點"),
    PROGRESS_TYPE_SET_FUNCTION_SPECTATOR_STEP_1_TITLE("Progress.type.set-function.spectator.step.1.title", "&a✔"),
    PROGRESS_TYPE_SET_FUNCTION_SPECTATOR_STEP_1_SUBTITLE("Progress.type.set-function.spectator.step.1.subtitle", "&f成功選擇A點 座標&e{}"),
    PROGRESS_TYPE_SET_FUNCTION_SPECTATOR_STEP_2_TIP("Progress.type.set-function.spectator.step.2.tip", "左鍵點選方塊選擇觀戰區域B點"),
    PROGRESS_TYPE_SET_FUNCTION_SPECTATOR_STEP_2_TITLE("Progress.type.set-function.spectator.step.2.title", "&a✔"),
    PROGRESS_TYPE_SET_FUNCTION_SPECTATOR_STEP_2_SUBTITLE("Progress.type.set-function.spectator.step.2.subtitle", "&f成功選擇B點 座標&e{}"),
    PROGRESS_TYPE_SET_FUNCTION_SPECTATOR_STEP_3_TIP("Progress.type.set-function.spectator.step.3.tip", "點選螢幕使當前位置作為觀戰玩家的傳送點"),
    PROGRESS_TYPE_SET_FUNCTION_SPECTATOR_STEP_3_TITLE("Progress.type.set-function.spectator.step.3.title", "&a✔"),
    PROGRESS_TYPE_SET_FUNCTION_SPECTATOR_STEP_3_SUBTITLE("Progress.type.set-function.spectator.step.3.subtitle", "&f成功選擇觀戰傳送點 座標&e{}"),
    PROGRESS_TYPE_SET_FUNCTION_SPECTATOR_STEP_4_TIP("Progress.type.set-function.spectator.step.4.tip", "輸入T或F分別表示是否向玩家展示對戰雙方的實時血量情況"),
    PROGRESS_TYPE_SET_FUNCTION_SPECTATOR_STEP_4_TITLE("Progress.type.set-function.spectator.step.4.title", "&a✔"),
    PROGRESS_TYPE_SET_FUNCTION_SPECTATOR_STEP_4_SUBTITLE("Progress.type.set-function.spectator.step.4.subtitle", "&f成功設定是否向玩家展示對戰雙方的實時血量情況：{}"),
    PROGRESS_TYPE_SET_FUNCTION_BAN_ENTITY_SPAWN_STEP_1_TIP("Progress.type.set-function.ban-entity-spawn.step.1.tip", "上傳實體白名單列表，輸入實體的列舉名後傳送即新增一種，輸入-l結束並上傳整個列表，允許只輸入-l跳過設定白名單"),
    PROGRESS_TYPE_SET_FUNCTION_BAN_ENTITY_SPAWN_STEP_1_TITLE("Progress.type.set-function.ban-entity-spawn.step.1.title", "&a✔"),
    PROGRESS_TYPE_SET_FUNCTION_BAN_ENTITY_SPAWN_STEP_1_SUBTITLE("Progress.type.set-function.ban-entity-spawn.step.1.subtitle", "&f成功上傳列舉列表 &b{}"),
    COMMAND_PARAMETER_PLAYER("Command.parameter.player", "玩家名"),
    COMMAND_PARAMETER_VALUE("Command.parameter.value", "值"),
    COMMAND_PARAMETER_ARENA_ID("Command.parameter.arena-id", "競技場ID"),
    COMMAND_PARAMETER_ARENA_EDIT_NAME("Command.parameter.arena-edit-name", "競技場編輯名"),
    COMMAND_PARAMETER_SOURCE_ARENA_ID("Command.parameter.source-arena-id", "源競技場ID"),
    COMMAND_PARAMETER_TARGET_ARENA_ID("Command.parameter.target-arena-id", "目標競技場ID"),
    COMMAND_PARAMETER_ARENA_TYPE("Command.parameter.arena-type", "型別"),
    COMMAND_PARAMETER_ARENA_FUNCTION_ID("Command.parameter.arena-function", "附加功能ID"),
    COMMAND_PARAMETER_LANGUAGE_FILE_NAME("Command.parameter.language-file-name", "檔名"),
    COMMAND_PARAMETER_POINT("Command.parameter.point", "積分數"),
    COMMAND_PARAMETER_PAGE("Command.parameter.page", "頁數"),
    COMMAND_PARAMETER_ROW("Command.parameter.row", "行數"),
    COMMAND_PARAMETER_COLUMN("Command.parameter.line", "列數"),
    COMMAND_PARAMETER_DESCRIPTION("Command.parameter.description", "描述語"),
    COMMAND_PARAMETER_VALUE_OR_CONTENT("Command.parameter.value-or-content", "值或內容"),
    COMMAND_PARAMETER_COMMAND_EXECUTOR("Command.parameter.command-executor", "執行身份"),
    COMMAND_PARAMETER_INDEX("Command.parameter.index", "序號"),
    COMMAND_PARAMETER_RANKING_TYPE("Command.parameter.ranking-type", "排行榜型別ID"),
    COMMAND_PARAMETER_RANKING_PAGE("Command.parameter.ranking-page", "排行榜頁碼"),
    COMMAND_PARAMETER_REASON("Command.parameter.reason", "原因"),
    COMMAND_CORRECT("Command.correct", "&e[糾錯提示] {command} &6[clickable]command::&7(點選鍵入)::&f點選快速輸入這條指令[clickable]",
            new String[][]{{"command", "", "{command}", ""}},
            "command"),
    COMMAND_SUGGEST("Command.suggest", "&7你想輸入的是否為:&f {command} &6[clickable]command::&f(點選鍵入)::&f點選快速輸入這條指令[clickable]",
            new String[][]{{"command", "", "{command}", ""}},
            "command"),
    COMMAND_TITLE_ADMINHELP("Command.title.adminhelp", "&d管理員幫助"),
    COMMAND_TITLE_HELP("Command.title.help", "&d玩家幫助"),
    COMMAND_TITLE_POINT("Command.title.point", "&d積分幫助"),
    COMMAND_TITLE_SHOP("Command.title.shop", "&d積分兌換商城幫助"),
    COMMAND_TITLE_LEVEL("Command.title.level", "&d等級系統幫助"),
    COMMAND_TITLE_BLACKLIST("Command.title.blacklist", "&d黑名單幫助"),
    COMMAND_TITLE_LOBBY("Command.title.lobby", "&d大廳幫助"),
    COMMAND_TITLE_ARENA("Command.title.arena", "&d競技場幫助"),
    COMMAND_TITLE_RANK("Command.title.rank", "&d排行榜幫助"),
    COMMAND_MAIN_HELP("Command.main.help", "&f檢視基礎幫助"),
    COMMAND_MAIN_ADMIN_HELP("Command.main.admin-help", "&f檢視管理員幫助"),
    COMMAND_SUB_ARENA_SERIES_DESCRIPTION("Command.sub.arena.series-description", "&b&l檢視競技場相關指令幫助"),
    COMMAND_SUB_SHOP_SERIES_DESCRIPTION("Command.sub.shop.series-description", "&b&l檢視積分商城相關指令幫助"),
    COMMAND_SUB_POINT_SERIES_DESCRIPTION("Command.sub.point.series-description", "&b&l檢視積分相關指令幫助"),
    COMMAND_SUB_LEVEL_SERIES_DESCRIPTION("Command.sub.level.series-description", "&b&l檢視PVP等級相關指令幫助"),
    COMMAND_SUB_RANK_SERIES_DESCRIPTION("Command.sub.rank.series-description", "&b&l檢視排行榜相關指令幫助"),
    COMMAND_SUB_LOBBY_SERIES_DESCRIPTION("Command.sub.lobby.series-description", "&b&l檢視大廳相關指令幫助"),
    COMMAND_SUB_BLACKLIST_SERIES_DESCRIPTION("Command.sub.blacklist.series-description", "&b&l檢視黑名單相關指令幫助"),
    COMMAND_SUB_BALANCE_DESCRIPTION("Command.sub.balance.description", "&b檢視與調整分數平衡設定"),
    COMMAND_SUB_DOCTOR_DESCRIPTION("Command.sub.doctor.description", "&b執行系統健康檢查"),
    COMMAND_SUB_QUEUE_DESCRIPTION("Command.sub.queue.description", "&b管理匹配佇列（音效、冷卻、除錯）"),
    COMMAND_SUB_UPDATE_DESCRIPTION("Command.sub.update.description", "&b檢查與下載插件更新"),
    COMMAND_SUB_STOP_DESCRIPTION("Command.sub.stop.description", "&b&l強制停止某個競技場的比賽"),
    COMMAND_SUB_RELOAD_DESCRIPTION("Command.sub.reload.description", "&b&l過載配置檔案和所有語言檔案"),
    COMMAND_SUB_START_DESCRIPTION("Command.sub.start.description", "&b開啟競技場選擇面板"),
    COMMAND_SUB_SEND_DESCRIPTION("Command.sub.send.description", "&b向某個玩家傳送比賽邀請"),
    COMMAND_SUB_ACCEPT_DESCRIPTION("Command.sub.accept.description", "&b接受（來自某個玩家的）比賽邀請"),
    COMMAND_SUB_DECLINE_DESCRIPTION("Command.sub.decline.description", "&b謝絕（來自某個玩家的）比賽邀請"),
    COMMAND_SUB_JOIN_DESCRIPTION("Command.sub.wait.description", "&b加入某個競技場或其等待佇列"),
    COMMAND_SUB_SHOP_DESCRIPTION("Command.sub.shop.description", "&b開啟積分兌換商城"),
    COMMAND_SUB_LOBBY_DESCRIPTION("Command.sub.lobby.description", "&b前往大廳"),
    COMMAND_SUB_SPECTATE_DESCRIPTION("Command.sub.spectate.description", "&b觀看某個競技場的比賽"),
    COMMAND_SUB_QUIT_DESCRIPTION("Command.sub.quit.description", "&b退出當前比賽(比賽時使用)"),
    COMMAND_SUB_RECORD_DESCRIPTION("Command.sub.record.description", "&b開啟比賽記錄面板"),
    COMMAND_SUB_RECORD_EXPORT_DESCRIPTION("Command.sub.record.export-description", "&b匯出玩家戰報（json/csv）"),
    COMMAND_SUB_STATS_DESCRIPTION("Command.sub.stats.description", "&b查看玩家統計資訊"),
    COMMAND_SUB_LANG_DESCRIPTION("Command.sub.lang.description", "&b切換語言環境"),
    COMMAND_SUB_POINT_VIEW_SELF_DESCRIPTION("Command.sub.point.view-self-description", "&b檢視自己的積分"),
    COMMAND_SUB_POINT_ADD_DESCRIPTION("Command.sub.point.add-description", "&b為某個玩家增加積分"),
    COMMAND_SUB_POINT_SET_DESCRIPTION("Command.sub.point.set-description", "&b為某個玩家設定積分"),
    COMMAND_SUB_POINT_VIEW_PLAYER_DESCRIPTION("Command.sub.point.view-player-description", "&b檢視某個玩家的積分"),
    COMMAND_SUB_POINT_VIEW_SELF("Command.sub.point.view-self", "&b我的積分：&d{point}",
            "point"),
    COMMAND_SUB_POINT_ADD_SUCCESSFULLY("Command.sub.point.add-successfully", "&a成功新增為玩家 &b{player} &a新增 &6{point} &a積分",
            "player", "point"),
    COMMAND_SUB_POINT_SET_SUCCESSFULLY("Command.sub.point.set-successfully", "&a成功新增將玩家 &b{player} &a的積分設定為 &6{point}",
            "player", "point"),
    COMMAND_SUB_POINT_VIEW_PLAYER("Command.sub.point.view-player", "&a玩家 &b{player} &a的積分為 &6{point}",
            "player", "point"),
    COMMAND_SUB_LANG_LIST_HEADING("Command.sub.lang.list-heading", "&b語言檔案如下："),
    COMMAND_SUB_LANG_LIST_BODY("Command.sub.lang.list-body", "&2&l{index}. &a{file}[clickable]switch::&7(點選切換)::&f點選將自己的語言環境切換為：&a{file}[clickable]",
            new String[][]{{"switch", "/dueltime lang {file}", "", ""}},
            "index", "file"),
    COMMAND_SUB_LANG_LIST_ENDING("Command.sub.lang.list-ending", "&b共計 &3&l{number} &b個檔案",
            "number"),
    COMMAND_SUB_LANG_NO_FILES_INSTALLED("Command.sub.lang.no-file-installed", "&c伺服器未裝載任何其他語言檔案"),
    COMMAND_SUB_LANG_THE_FILE_NOT_EXISTS("Command.sub.lang.the-file-not-exists", "&c不存在名為 &e'{file}' &c的語言檔案",
            "file"),
    COMMAND_SUB_LANG_SWITCH_SUCCESSFULLY("Command.sub.lang.switch-successfully", "&a切換成功！當前語言環境：{language}",
            "language"),
    COMMAND_SUB_BLACKLIST_ADD_DESCRIPTION("Command.sub.blacklist.add-description", "&b將某個玩家新增到黑名單中"),
    COMMAND_SUB_BLACKLIST_REMOVE_DESCRIPTION("Command.sub.blacklist.remove-description", "&b把某個玩家從黑名單中移除"),
    COMMAND_SUB_BLACKLIST_VIEW_DESCRIPTION("Command.sub.blacklist.view-description", "&b檢視黑名單列表"),
    COMMAND_SUB_BLACKLIST_ADD_SUCCESSFULLY("Command.sub.blacklist.add-successfully", "&a成功將玩家 &b{player} &a新增到黑名單中",
            "player"),
    COMMAND_SUB_BLACKLIST_REMOVE_SUCCESSFULLY("Command.sub.blacklist.remove-successfully", "&a成功將玩家 &b{player} &a從黑名單中移除",
            "player"),
    COMMAND_SUB_BLACKLIST_THE_PLAYER_HAS_BEEN_IN("Command.sub.blacklist.the-player-has-been-in", "&c玩家 &e{player} &c已經在黑名單中了",
            "player"),
    COMMAND_SUB_BLACKLIST_THE_PLAYER_NOT_FOUND("Command.sub.blacklist.the-player-not-found", "&c玩家 &e'{player}' &c本來就不在黑名單中",
            "player"),
    COMMAND_SUB_BLACKLIST_VIEW_EMPTY("Command.sub.blacklist.view-empty", "&c當前黑名單中沒有任何玩家"),
    COMMAND_SUB_BLACKLIST_VIEW_HEADING("Command.sub.blacklist.view-heading", "&b黑名單如下："),
    COMMAND_SUB_BLACKLIST_VIEW_BODY("Command.sub.blacklist.view-body", "&2&l{index}. &a{player}[clickable]remove::&7(點選移除)::&f點選從黑名單中移除玩家：&a{player}[clickable]",
            new String[][]{{"remove", "/dueltime blacklist remove {player}", "", ""}},
            "index", "player"),
    COMMAND_SUB_BLACKLIST_VIEW_ENDING("Command.sub.blacklist.view-ending", "&b共計 &3&l{number} &b個玩家",
            "number"),
    COMMAND_SUB_LEVEL_VIEW_SELF_DESCRIPTION("Command.sub.level.view-self-description", "&b檢視自己的等級與經驗資訊"),
    COMMAND_SUB_LEVEL_VIEW_PLAYER_DESCRIPTION("Command.sub.level.view-player-description", "&b檢視某個玩家的等級與經驗"),
    COMMAND_SUB_LEVEL_EXP_DESCRIPTION("Command.sub.level.exp-description", "&b為某個玩家增加/設定經驗"),
    COMMAND_SUB_LEVEL_VIEW_SELF("Command.sub.level.view-self", new String[]{
            "&7&m───&f&l&m────────────────────────&7&m───",
            "    &a當前等級: &e{level}",
            "    &a當前段位: &f{tier_title}",
            "    &a經驗總量: &3{total_exp}",
            "    &a升級所需: &3{need_exp}",
            "    &a升級進度: &f{progress_bar_level_20_■_2_7} &f({progress_value}%)",
            "&7&m───&f&l&m────────────────────────&7&m───"
    },
            "level", "tier_title", "total_exp", "need_exp", "progress_bar_level", "progress_value"),
    COMMAND_SUB_LEVEL_VIEW_PLAYER("Command.sub.level.view-player", new String[]{
            "&7&m───&f&l&m────────────────────────&7&m───",
            "    &a玩家名稱: &b{player}",
            "    &a當前等級: &e{level}",
            "    &a當前段位: &f{tier_title}",
            "    &a經驗總量: &3{exp}",
            "&7&m───&f&l&m────────────────────────&7&m───"
    }, "player", "level", "tier_title", "exp"),
    COMMAND_SUB_LEVEL_ADD_SUCCESSFULLY("Command.sub.level.add-successfully", "&a成功新增為玩家 &b{player} &a新增 &6{exp} &a點經驗",
            "player", "exp"),
    COMMAND_SUB_LEVEL_SET_SUCCESSFULLY("Command.sub.level.set-successfully", "&a成功新增將玩家 &b{player} &a的經驗設定為 &6{exp}",
            "player", "exp"),
    COMMAND_SUB_STOP_FAIL_ARENA_NOT_EXISTS("Command.sub.stop.fail-arena-not-exists", "&c競技場 &e'{arena}'&c 不存在，無法執行停止操作。請檢查輸入",
            "arena"),
    COMMAND_SUB_STOP_FAIL_NO_GAME("Command.sub.stop.fail-no-game", "&c競技場 &e{arena}&c 當前不處於比賽狀態",
            "arena"),
    COMMAND_SUB_STOP_TENTATIVELY("Command.sub.stop.tentatively", "&7正在強制停止模式為 &3{arena_type} &7的競技場 &b{arena}&a 上的比賽...",
            "arena_type", "arena_name"),
    COMMAND_SUB_RELOAD_START("Command.sub.reload.start", "&7開始過載配置檔案並嘗試應用..."),
    COMMAND_SUB_RELOAD_SUCCESSFULLY("Command.sub.reload.successfully", "&a過載完成！歷時 &b{time} &a毫秒",
            "time"),
    ITEM_GUI_SHOP_BUTTON_PREVIOUS_PAGE_NAME("Item.gui.shop.button-previous-page", "&9上一頁"),
    ITEM_GUI_SHOP_BUTTON_NEXT_PAGE_NAME("Item.gui.shop.button-next-page", "&9下一頁"),
    ITEM_GUI_SHOP_REWARD_INFORMATION("Item.gui.shop.reward-information", new String[]{
            "",
            "&e&l[兌換所需] &6{point}點積分",
            "&e&l[本服已兌] &6{volume}份",
            "&e&l[獎品描述] &7{description}",
            "",
    },
            "point", "volume", "description"),
    ITEM_GUI_SHOP_REWARD_LEVEL_LIMIT_TIP_YES("Item.gui.shop.reward-level-limit-tip-yes", "&2&l[&a&l!&2&l]&7你已達到兌換此獎品所需要的等級: {level}",
            "level"),
    ITEM_GUI_SHOP_REWARD_REDEEM_TIP_YES("Item.gui.shop.reward-redeem-tip-yes", "&b點選兌換：&b&l{point_now}&3/{point_need}",
            "point_now", "point_need"),
    ITEM_GUI_SHOP_REWARD_REDEEM_TIP_NO_ENOUGH_POINT("Item.gui.shop.reward-redeem-tip-no-enough-point", "&c積分不足：&c&l{point_now}&e/{point_need}",
            "point_now", "point_need"),
    ITEM_GUI_SHOP_REWARD_REDEEM_TIP_NO_ENOUGH_LEVEL("Item.gui.shop.reward-redeem-tip-no-enough-level", "&c等級不足：&c&l{level_now}&e/{level_need}",
            "level_now", "level_need"),
    ITEM_GUI_RECORD_SHOW_TIP("Item.gui.record.show-tip", "&b[左鍵點選] &f向聊天框中傳送本記錄"),
    ITEM_GUI_RECORD_PRINT_TIP("Item.gui.record.print-tip", "&d[右鍵點選] &f將本記錄列印到手持的紙張上&7(需要消耗{point}積分)",
            "point"),
    ITEM_GUI_START_ARENA_INFORMATION("Item.gui.start.arena-information", new String[]{
            "",
            "&f狀態: &f{state}",
            "&f人數: &a{now_number}&2/{max_number}",
            "",
            "{button_message}"
    },
            "state", "now_number", "max_number", "button_message"),
    ITEM_GUI_START_ARENA_STATE_WAITING("Item.gui.start.arena-state.waiting", "&a等待中 &7(&f{count}&7人)",
            "count"),
    ITEM_GUI_START_ARENA_STATE_IN_PROGRESS_CLOSED("Item.gui.start.arena-state.in-progress-closed", "&c進行中&7(不可中途加入)"),
    ITEM_GUI_START_ARENA_STATE_IN_PROGRESS_OPENED("Item.gui.start.arena-state.in-progress-opened", "&b進行中&3(允許中途加入)"),
    ITEM_GUI_START_ARENA_STATE_DISABLED("Item.gui.start.arena-state.disabled", "&c停用中"),
    ITEM_GUI_START_ARENA_BUTTON_MESSAGE_WAITING_START("Item.gui.start.arena-button-message.waiting-start", "&b&l[點選等待]"),
    ITEM_GUI_START_ARENA_BUTTON_MESSAGE_WAITING_STOP("Item.gui.start.arena-button-message.waiting-stop", "&3&l[點選取消等待]"),
    ITEM_GUI_START_ARENA_BUTTON_MESSAGE_IN_PROGRESS_CLOSED("Item.gui.start.arena-button-message.in-progress-closed", "&c&l[不可加入]"),
    ITEM_GUI_START_ARENA_BUTTON_MESSAGE_IN_PROGRESS_OPENED("Item.gui.start.arena-button-message.in-progress-opened", "&a&l[點選加入]"),
    ITEM_GUI_START_ARENA_BUTTON_MESSAGE_IN_PROGRESS_OPENED_FULL("Item.gui.start.arena-button-message.in-progress-opened-full", "&c&l[人數已滿]"),
    ITEM_GUI_START_ARENA_BUTTON_MESSAGE_DISABLED("Item.gui.start.arena-button-message.disabled", "&c&l[不可用]"),
    GUI_ALREADY_THE_FIRST_PAGE("GUI.already-the-first-page", "&c已經是第一頁了"),
    GUI_ALREADY_THE_LAST_PAGE("GUI.already-the-last-page", "&c已經是最後一頁了"),
    GUI_TYPE_SHOP_TITLE("GUI.type.shop.title", "&9積分兌換商城"),
    GUI_TYPE_SHOP_EMPTY("GUI.type.shop.empty", "&c積分兌換商城暫未設定任何獎品"),
    GUI_TYPE_SHOP_REDEEM_UNSUCCESSFULLY_INSUFFICIENT_POINTS("GUI.type.shop.redeem-unsuccessfully-insufficient-points", "&c積分不足！你需要 &e{point_need} &c才能兌換這個獎品，而你目前只有 &e{point_now}",
            "point_need", "point_now"),
    GUI_TYPE_SHOP_REDEEM_UNSUCCESSFULLY_INSUFFICIENT_LEVEL("GUI.type.shop.redeem-unsuccessfully-insufficient-level", "&c等級不足！你需要達到 &e{level_need} &c級兌換這個獎品，而你目前為 &e{level_now} &c級，請繼續努力",
            "level_need", "level_now"),
    GUI_TYPE_SHOP_REDEEM_SUCCESSFULLY("GUI.type.shop.redeem-successfully", "&b兌換成功！獎品已傳送到你的揹包"),
    GUI_TYPE_SHOP_REDEEM_SUCCESSFULLY_BUT_DROP("GUI.type.shop.redeem-successfully-but-drop", "&3兌換成功！&b&n但由於揹包空間不足，兌換到的獎品以掉落物的形式在你當前的位置出現，總共 {number} 種",
            "number"),
    GUI_TYPE_RECORD_TITLE("GUI.type.record.title", "&9{player}的比賽記錄",
            "player"),
    GUI_TYPE_RECORD_EMPTY("GUI.type.record.empty", "&c暫時沒有任何比賽記錄"),
    GUI_TYPE_RECORD_SHOW_FREQUENTLY("GUI.type.record.show-frequently", "&c請等待 &e{time} &c秒再展示比賽記錄",
            "time"),
    GUI_TYPE_RECORD_SHOW_CONTENT("GUI.type.record.show-content", "&f{player} &7: [clickable]show::&b[我的比賽記錄]::{content}[clickable]&7(滑鼠移動到文字上方檢視)",
            new String[][]{{"show", "", "", ""}},
            "player", "content"),
    GUI_TYPE_RECORD_PRINT_INSUFFICIENT_POINT("GUI.type.record.print-insufficient-point", "&c需要 &e{point_need} &c點積分才能列印一次比賽記錄，而你現在只有 &e{point_now} &c點",
            "point_need", "point_now"),
    GUI_TYPE_RECORD_PRINT_FAIL_NO_PAPER_IN_HAND("GUI.type.record.print-fail-no-paper-in-hand", "&c請先把紙張拿在手上"),
    GUI_TYPE_RECORD_PRINT_FAIL_PAPER_HAS_META("GUI.type.record.print-fail-paper-has-meta", "&c列印用的紙張應為普通的紙"),
    GUI_TYPE_RECORD_PRINT_SUCCESSFULLY("GUI.type.record.print-successfully", "&a列印成功！請檢視你的紙張"),
    GUI_TYPE_START_TITLE("GUI.type.start.title", "&9競技場列表"),
    GUI_TYPE_START_EMPTY("GUI.type.start.empty", "&c伺服器未建立任何競技場"),
    GUI_TYPE_START_USE_WHILE_IN_GAME("GUI.type.start.use-while-in-game", "&c你現在正處於競技場 &e{arena}&c 的比賽中，無法執行此操作",
            "arena"),
    GUI_TYPE_START_WAITING_OPERATION_COOLDOWN("GUI.type.start.state.waiting-operation-cooldown", "&7請不要過於頻繁地操作等待功能"),
    GUI_TYPE_START_STATE_IN_PROGRESS_CLOSED("GUI.type.start.state.in-progress-closed", "&c競技場 &e{arena}&c 不允許中途加入",
            "arena"),
    GUI_TYPE_START_STATE_IN_PROGRESS_OPENED_FULL("GUI.type.start.state.in-progress-opened-full", "&c競技場 &e{arena}&c 已經滿人，暫不可加入",
            "arena"),
    GUI_TYPE_START_STATE_IN_PROGRESS_OPENED("GUI.type.start.state.in-progress-opened", "&a正在加入競技場：&b{arena}",
            "arena"),
    GUI_TYPE_START_STATE_DISABLED("GUI.type.start.state.disabled", "&c競技場 &e{arena}&c 處於停用狀態！",
            "arena"),
    GUI_TYPE_ITEM_DETAIL_TITLE("GUI.type.item-display.title", "&9物品詳情"),
    COMMAND_SUB_SHOP_HELP_DESCRIPTION("Command.sub.shop.help-description", "&b&l檢視積分兌換商城的管理員幫助"),
    COMMAND_SUB_SHOP_ADD_DESCRIPTION("Command.sub.shop.add-description", "&b將手上的物品作為獎品新增到積分兌換商城中"),
    COMMAND_SUB_SHOP_DELETE_DESCRIPTION("Command.sub.shop.delete-description", "&b刪除某個獎品"),
    COMMAND_SUB_SHOP_RESET_DESCRIPTION("Command.sub.shop.reset-description", "&b為某個獎品重設價格/描述/等級限制"),
    COMMAND_SUB_SHOP_COMMAND_ADD_DESCRIPTION("Command.shop.command.add-description", "&b為某個獎品新增一條兌換後執行的指令"),
    COMMAND_SUB_SHOP_COMMAND_REMOVE_DESCRIPTION("Command.shop.command.remove-description", "&b為某個獎品移除一條兌換後執行的指令"),
    COMMAND_SUB_SHOP_COMMAND_CLEAR_DESCRIPTION("Command.sub.shop.command.clear-description", "&b移除某個獎品的所有兌換後指令"),
    COMMAND_SUB_SHOP_COMMAND_LIST_DESCRIPTION("Command.sub.shop.command.list-description", "&b檢視某個獎品的所有兌換後指令"),
    COMMAND_SUB_SHOP_ADD_SUCCESSFULLY("Command.sub.shop.add-successfully", "&a獎品新增成功！&2(位置：第{page}頁，第{row}行，第{column}行)",
            "page", "row", "column"),
    COMMAND_SUB_SHOP_ADD_EMPTY_ITEMSTACK("Command.sub.shop.add-empty-itemstack", "&c請把要上架的物品拿在手上！"),
    COMMAND_SUB_SHOP_DELETE_SUCCESSFULLY("Command.sub.shop.delete-successfully", "&a獎品刪除成功！&2(位置：第{page}頁，第{row}行，第{column}行)",
            "page", "row", "column"),
    COMMAND_SUB_SHOP_INVALID_LOC("Command.sub.shop.invalid-loc", "&c不存在位置為&e'第{page}頁，第{row}行，第{column}行'&c的獎品，請重新檢查輸入",
            "page", "row", "column"),
    COMMAND_SUB_SHOP_RESET_POINT_SUCCESSFULLY("Command.sub.shop.reset-point-successfully", "&a成功修改兌換積分需求為 &b{point} &a點！&2(位置：第{page}頁，第{row}行，第{column}行)",
            "point", "page", "row", "column"),
    COMMAND_SUB_SHOP_RESET_DESCRIPTION_SUCCESSFULLY("Command.sub.shop.reset-description-successfully", "&a成功修改獎品的描述為&f'&7{description}&f'  &2(位置：第{page}頁，第{row}行，第{column}行)",
            "description", "page", "row", "column"),
    COMMAND_SUB_SHOP_RESET_LEVEL_LIMIT_SUCCESSFULLY("Command.sub.shop.reset-level-limit-successfully", "&a成功修改兌換的等級限制為 &b{level} &a級！ &2(位置：第{page}頁，第{row}行，第{column}行)",
            "level", "page", "row", "column"),
    COMMAND_SUB_SHOP_COMMAND_ADD_SUCCESSFULLY("Command.sub.shop.command-add-successfully", "&a成功新增兌換後指令 &f{command_content}&f &a執行身份為&b{command_executor} &2(位置：第{page}頁，第{row}行，第{column}行)",
            "command_content", "command_executor", "page", "row", "column"),
    COMMAND_SUB_SHOP_COMMAND_ADD_TIP_COMMAND_EXECUTOR("Command.sub.shop.command-add-tip-executor",
            new String[]{
                    "&e[用法提示]",
                    "&7'{enter}' &f不是一個有效的執行身份",
                    "&f執行身份：&b'player'&f或&b'p'&f代表&b玩家；&d'player'&f或&d'p'&f代表&d玩家；&e'player'&f或&e'p'&f代表&e後臺",
                    "&f示例：&e{command_entered_corrected} [clickable]type::&7(點選鍵入)::&f點選快速鍵入這條指令[clickable]"
            },
            new String[][]{{"type", "", "{command_entered_corrected}", ""}},
            "enter", "command_entered_corrected"),
    COMMAND_SUB_SHOP_COMMAND_REMOVE_SUCCESSFULLY("Command.sub.shop.command-remove-successfully", "&a成功刪除兌換後指令 &f'&7/{command}&f' &2(獎品位置：第{page}頁，第{row}行，第{column}行；指令序號：{index})",
            "command", "page", "row", "column", "index"),
    COMMAND_SUB_SHOP_COMMAND_INDEX_IS_NOT_FOUND("Command.sub.shop.command-index-is-not-found", "&e'{index}' &c不是一個正確的指令序號，請檢查輸入",
            "index"),
    COMMAND_SUB_SHOP_COMMAND_CLEAR_SUCCESSFULLY("Command.sub.shop.command-clear-successfully", "&a成功清除了 &b{number} &a條兌換後指令 &2(位置：第{page}頁，第{row}行，第{column}行)",
            "number", "page", "row", "column"),
    COMMAND_SUB_SHOP_COMMAND_EMPTY("Command.sub.shop.command-empty", "&c該獎品沒有設定任何兌換後執行的指令"),
    COMMAND_SUB_SHOP_COMMAND_LIST_HEADING("Command.sub.shop.command-list-heading", "&b兌換後指令列表如下： &3(位置：第{page}頁，第{row}行，第{column}行)",
            "page", "row", "column"),
    COMMAND_SUB_SHOP_COMMAND_LIST_BODY("Command.sub.shop.command-list-body", "&2&l{index}. &a/{command_content} &f(執行身份:{command_executor}) [clickable]remove::&7[點選移除]::&f點選移除這條指令[clickable]",
            new String[][]{{"remove", "/dueltime shop command remove {page} {row} {column} {index}", "", ""}},
            "index", "command_content", "command_executor", "page", "row", "column"),
    COMMAND_SUB_SHOP_COMMAND_LIST_ENDING("Command.sub.shop.command-list-ending", "&b共計 &3&l{number} &b條兌換後指令",
            "number"),
    COMMAND_SUB_SEND_FAIL_SELF_IN_BLACK_LIST("Command.sub.send.fail-self-in-black-list", "&c當前你處於黑名單中，無法發起比賽邀請"),
    COMMAND_SUB_SEND_FAIL_SEND_TO_SELF("Command.sub.send.fail-send-to-self", "&c你不能向自己傳送比賽邀請，請輸入其他玩家名"),
    COMMAND_SUB_SEND_FAIL_NO_ARENAS("Command.sub.send.fail-no-arenas", "&c伺服器沒有設定任何競技場，無法發起比賽邀請"),
    COMMAND_SUB_SEND_FAIL_OFFLINE("Command.sub.send.fail-offline", "&c無法傳送比賽邀請：玩家 &e'{player}' &c不線上或不存在",
            "player"),
    COMMAND_SUB_SEND_FAIL_RECIPIENT_IN_BLACK_LIST("Command.sub.send.fail-recipient-in-black-list", "&c當前玩家 &e{player} &c處於黑名單中，無法向其傳送比賽邀請",
            "player"),
    COMMAND_SUB_SEND_FAIL_INVALID_ARENA_ID("Command.sub.send.fail-invalid-arena-id", "&c不存在編輯名或ID為 &e'{enter}' &c的競技場，請檢查輸入",
            "enter"),
    COMMAND_SUB_SEND_FAIL_ARENA_DISABLED("Command.sub.send.fail-arena-disabled", "&c競技場 &e{arena} &c處於停用狀態，請換一個指定",
            "arena"),
    COMMAND_SUB_SEND_FAIL_FREQUENTLY("Command.sub.send.fail-frequently", "&c你在 &e{second} &c秒前已經向玩家 &e{player} &c傳送過比賽邀請了，請等待對方處理",
            "second", "player"),
    COMMAND_SUB_SEND_SUCCESSFULLY("Command.sub.send.successfully", "&a成功向玩家 &b{player} &a傳送比賽邀請，請等待對方處理",
            "player"),
    COMMAND_SUB_SEND_RECEIVE("Command.sub.send.receive",
            new String[]{
                    "&7&m───&f&l&m────────────────────────&7&m───",
                    "",
                    " &b收到來自&e{player}&b的比賽邀請  [clickable]accept::&a&l[✔]::&a點選接受邀請[clickable] [clickable]decline::&c&l[✘]::&c點選謝絕邀請[clickable]",
                    "",
                    "&7&m───&f&l&m────────────────────────&7&m───"
            },
            new String[][]{{"accept", "/dueltime accept", "", ""}, {"decline", "/dueltime decline", "", ""}},
            "player"),
    COMMAND_SUB_SEND_RECEIVE_NOTIFY_DESIGNATED_ARENA("Command.sub.send.receive-notify-designated-arena", "&3&l[!]&f對方指定了競技場：&e{arena_name}&7({arena_type}&7)",
            "arena_name", "arena_type"),
    COMMAND_SUB_ACCEPT_FAIL_NONE("Command.sub.accept.fail-none", "&c你沒有任何待接受的邀請"),
    COMMAND_SUB_ACCEPT_FAIL_TIME_OUT("Command.sub.accept.fail-time-out", "&c失效邀請：玩家 &e{player} &c向你傳送的邀請因為長時間未被處理而失效了",
            "player"),
    COMMAND_SUB_ACCEPT_FAIL_OFFLINE("Command.sub.accept.fail-offline", "&c無效邀請：玩家 &e'{player}' &c不線上或不存在",
            "player"),
    COMMAND_SUB_ACCEPT_FAIL_HAS_NOT_SENT("Command.sub.accept.fail-has-not-sent", "&c無效邀請：玩家 &e'{player}' &c還未向你傳送過邀請",
            "player"),
    COMMAND_SUB_ACCEPT_FAIL_NO_ARENAS("Command.sub.accept.fail-has-no-arenas", "&c伺服器沒有設定任何競技場，無法開始比賽"),
    COMMAND_SUB_ACCEPT_FAIL_NO_AVAILABLE_ARENAS("Command.sub.accept.fail-has-no-available-arenas", "&c伺服器還未設定最小開賽人數小於3的競技場"),
    COMMAND_SUB_ACCEPT_FAIL_NO_AVAILABLE_ARENAS_TEMPORARILY("Command.sub.accept.fail-has-no-available-arenas-temporarily", "&c當前暫時沒有可用的最小開賽人數小於3的競技場"),
    COMMAND_SUB_ACCEPT_SUCCESS_RECEIVER("Command.sub.accept.success-receiver", "&a已接受玩家 &b{player} &a的邀請",
            "player"),
    COMMAND_SUB_ACCEPT_SUCCESS_SENDER("Command.sub.accept.success-sender", "&a玩家 &b{player} &a接受了你的邀請",
            "player"),
    COMMAND_SUB_ACCEPT_SUCCESS_NOTIFY_RANDOMLY_CHOSEN_ARENA("Command.sub.accept.success-notify-randomly-chosen-arena", "&b&l[!]&3由於沒有指定競技場，系統自動為你們隨機選擇了競技場&f{arena_name}&7(&f{arena_type}&7)",
            "arena_name", "arena_type"),
    COMMAND_SUB_ACCEPT_CHOOSE_LIST_HEADING("Command.sub.accept.choose-list-heading", "&b當前你有多個待處理的邀請，請選擇要接受的："),
    COMMAND_SUB_ACCEPT_CHOOSE_LIST_BODY("Command.sub.accept.choose-list-body", "&f&l{index}. &f{player} &7(指定競技場: {arena}) [clickable]accept::&a&l[接受]::&a點選接受邀請[clickable]",
            new String[][]{
                    {"accept", "/dueltime accept {player}", "", ""}},
            "index", "arena", "player"),
    COMMAND_SUB_ACCEPT_CHOOSE_LIST_ENDING("Command.sub.accept.choose-list-ending", "&b共計 &3&l{number} &b條待處理邀請",
            "number"),
    COMMAND_SUB_DECLINE_FAIL_NONE("Command.sub.accept.decline-none", "&c你沒有任何待拒絕的邀請"),
    COMMAND_SUB_DECLINE_FAIL_TIME_OUT("Command.sub.decline.fail-time-out", "&c失效邀請：玩家 &e{player} &c向你傳送的邀請因為長時間未被處理而失效了",
            "player"),
    COMMAND_SUB_DECLINE_FAIL_OFFLINE("Command.sub.decline.fail-offline", "&c無效邀請：玩家 &e'{player}' &c不線上或不存在",
            "player"),
    COMMAND_SUB_DECLINE_FAIL_HAS_NOT_SENT("Command.sub.decline.fail-has-not-sent", "&c無效邀請：玩家 &e'{player}' &c還未向你傳送過邀請",
            "player"),
    COMMAND_SUB_DECLINE_SUCCESS_RECEIVER("Command.sub.decline.success-receiver", "&a已拒絕玩家 &b{player} &a的邀請",
            "player"),
    COMMAND_SUB_DECLINE_SUCCESS_SENDER("Command.sub.decline.success-sender", "&c玩家 &6{player} &c謝絕了你的邀請",
            "player"),
    COMMAND_SUB_DECLINE_CHOOSE_LIST_HEADING("Command.sub.decline.choose-list-heading", "&b當前你有多個待處理的邀請，請選擇要拒絕的："),
    COMMAND_SUB_DECLINE_CHOOSE_LIST_BODY("Command.sub.decline.choose-list-body", "&f&l{index}. &f{player} [clickable]decline::&c&l[拒絕]::&c點選拒絕邀請[clickable]",
            new String[][]{
                    {"decline", "/dueltime decline {player}", "", ""}},
            "index", "player"),
    COMMAND_SUB_DECLINE_CHOOSE_LIST_ENDING("Command.sub.decline.choose-list-ending", "&b共計 &3&l{number} &b條待處理邀請",
            "number"),

    COMMAND_SUB_START_FAIL_SELF_IN_BLACK_LIST("Command.sub.start.fail-self-in-black-list", "&c當前你處於黑名單中，無法啟動開始面板"),
    COMMAND_SUB_JOIN_FAIL_ARENA_NOT_EXISTS("Command.sub.join.arena-not-exists", "&c競技場 &e'{arena}'&c 不存在，無法加入。請檢查輸入",
            "arena"),
    COMMAND_SUB_JOIN_FAIL_ARENA_DISABLED("Command.sub.join.fail-arena-disabled", "&c競技場 &e{arena}&c 處於停用狀態，暫不可加入",
            "arena"),
    COMMAND_SUB_JOIN_FAIL_ARENA_IN_PROGRESS_CLOSED("Command.sub.join.arena-in-progress-closed", "&c競技場 &e{arena}&c 不允許中途加入！",
            "arena"),
    COMMAND_SUB_JOIN_FAIL_ARENA_IN_PROGRESS_OPENED_FULL("Command.sub.join.arena-in-progress-opened-full", "&c競技場 &e{arena}&c 人數已滿，請稍後再嘗試加入",
            "arena"),
    COMMAND_SUB_JOIN_GAME_TENTATIVELY("Command.sub.join.game-tentatively", "&a正在嘗試加入競技場：&b{arena}",
            "arena"),
    COMMAND_SUB_LOBBY_HELP_DESCRIPTION("Command.sub.lobby.help-description", "&b檢視大廳的管理員幫助"),
    COMMAND_SUB_LOBBY_SET_DESCRIPTION("Command.sub.lobby.set-description", "&b將當前所在位置設定為大廳"),
    COMMAND_SUB_LOBBY_DELETE_DESCRIPTION("Command.sub.lobby.delete-description", "&b刪除大廳"),
    COMMAND_SUB_LOBBY_NONE("Command.sub.lobby.none", "&c伺服器未設定大廳傳送點"),
    COMMAND_SUB_LOBBY_SET_SUCCESSFULLY("Command.sub.lobby.set-successfully", "&a成功設定大廳傳送點為你當前位置"),
    COMMAND_SUB_LOBBY_UPDATE_SUCCESSFULLY("Command.sub.lobby.update-successfully", "&a大廳傳送點已更新為你當前位置"),
    COMMAND_SUB_LOBBY_DELETE_FAIL_NONE("Command.sub.lobby.delete-fail-none", "&c伺服器本來就沒設定大廳傳送點"),
    COMMAND_SUB_LOBBY_DELETE_SUCCESSFULLY("Command.sub.lobby.delete-successfully", "&a成功移除大廳傳送點"),
    COMMAND_SUB_ARENA_LIST_DESCRIPTION("Command.sub.arena.list-description", "&b檢視所有競技場"),
    COMMAND_SUB_ARENA_TYPE_DESCRIPTION("Command.sub.arena.info-description", "&b檢視本服已裝載的全部競技場型別"),
    COMMAND_SUB_ARENA_CREATE_DESCRIPTION("Command.sub.arena.create-description", "&b建立指定型別的競技場"),
    COMMAND_SUB_ARENA_VIEW_DESCRIPTION("Command.sub.arena.view-description", "&b檢視某個競技場的屬性資訊"),
    COMMAND_SUB_ARENA_DELETE_DESCRIPTION("Command.sub.arena.delete-description", "&b刪除某個競技場"),
    COMMAND_SUB_ARENA_FUNCTION_ADD_DESCRIPTION("Command.sub.arena.function-add-description", "&b為某個競技場增加一項附加功能"),
    COMMAND_SUB_ARENA_FUNCTION_REMOVE_DESCRIPTION("Command.sub.arena.function-remove-description", "&b為某個競技場移除一項附加功能"),
    COMMAND_SUB_ARENA_FUNCTION_RESET_DESCRIPTION("Command.sub.arena.function-reset-description", "&b為某個競技場的某項附加功能重設資料"),
    COMMAND_SUB_ARENA_FUNCTION_CLEAR_DESCRIPTION("Command.sub.arena.function-clear-description", "&b為某個競技場清除所有附加功能"),
    COMMAND_SUB_ARENA_FUNCTION_LIST_DESCRIPTION("Command.sub.arena.function-list-description", "&b檢視某個競技場的所有附加功能"),
    COMMAND_SUB_ARENA_FUNCTION_TYPE_DESCRIPTION("Command.sub.arena.function-type-description", "&b檢視某個競技場型別所定義的所有附加功能"),
    COMMAND_SUB_ARENA_FUNCTION_COPY_DESCRIPTION("Command.sub.arena.function-copy-description", "&b複製某個競技場的某個附加功能到另一個競技場"),
    COMMAND_SUB_ARENA_LIST_EMPTY("Command.sub.arena.list-empty", "&c伺服器內未設定任何競技場！"),
    COMMAND_SUB_ARENA_LIST_HEADING("Command.sub.arena.list-heading", "&b競技場列表如下："),
    COMMAND_SUB_ARENA_LIST_BODY("Command.sub.arena.list-body", "&f&l{index}. &f{arena_name} &3(型別:{arena_type} ID:{arena_id})",
            "index", "arena_name", "arena_type", "arena_id"),
    COMMAND_SUB_ARENA_LIST_ENDING("Command.sub.arena.list-ending", "&b共計 &3&l{number} &b個競技場",
            "number"),
    COMMAND_SUB_ARENA_TYPE_HEADING("Command.sub.arena.type-heading", "&b競技場型別如下："),
    COMMAND_SUB_ARENA_TYPE_BODY("Command.sub.arena.type-body", "&f&l{index}. &b{arena_type_name} &3(ID:{arena_type_id})",
            "index", "arena_type_name", "arena_type_id"),
    COMMAND_SUB_ARENA_TYPE_ENDING("Command.sub.arena.type-ending", "&b共計 &3&l{number} &b個型別",
            "number"),
    COMMAND_SUB_ARENA_CREATE_FAIL_INVALID_TYPE("Command.sub.arena.create-fail-invalid-type", "&c不存在 &e'{enter}' &c這個型別 [clickable]view::&f&n點選檢視所有型別[clickable]",
            new String[][]{
                    {"view", "/dueltime arena type", "", ""}},
            "enter"),
    COMMAND_SUB_ARENA_INVALID_ID("Command.sub.arena.invalid-id", "&c不存在ID為 &e'{enter}' &c的競技場 [clickable]view::&f&n點選檢視所有競技場對應的ID[clickable]",
            new String[][]{
                    {"view", "/dueltime arena list", "", ""}},
            "enter"),
    COMMAND_SUB_ARENA_TYPE_INVALID_ID("Command.sub.arena.type.invalid-id", "&c不存在型別ID為 &e'{enter}' &c的競技場 [clickable]view::&f&n點選檢視所有型別的競技場對應的ID[clickable]",
            new String[][]{
                    {"view", "/dueltime arena type", "", ""}},
            "enter"),
    COMMAND_SUB_ARENA_FUNCTION_INVALID_ID("Command.sub.arena.function.invalid-id", "&6{arena_type_entered} &c型別的競技場未定義ID為 &e'{function_entered}' &c的附加功能 [clickable]view::&f&n點選檢視{arena_type_entered}型別的競技場定義的所有功能ID[clickable]",
            new String[][]{
                    {"view", "/dueltime arena function type {arena_type_id}", "", ""}},
            "arena_type_entered", "function_entered", "arena_type_id"),
    COMMAND_SUB_ARENA_FUNCTION_TYPE_EMPTY("Command.sub.arena.function.type-empty", "&c{arena_type}型別的競技場沒有定義任何附加功能",
            "arena_type"),
    COMMAND_SUB_ARENA_FUNCTION_TYPE_HEADING("Command.sub.arena.function.type-heading", "&b{arena_type}型別的競技場定義的附加功能如下：",
            "arena_type"),
    COMMAND_SUB_ARENA_FUNCTION_TYPE_BODY("Command.sub.arena.function.type-body", new String[]{
            "&f&l{index}. &b{arena_function_name} &3(ID:{arena_function_id})",
            "&7描述：{arena_function_description}"},
            "index", "arena_function_name", "arena_function_id", "arena_function_description"),
    COMMAND_SUB_ARENA_FUNCTION_TYPE_ENDING("Command.sub.arena.function.type-ending", "&b共計 &3&l{number} &b種附加功能",
            "number"),
    COMMAND_SUB_ARENA_FUNCTION_COPY_INVALID_SOURCE_ARENA_ID("Command.sub.arena.function.copy-invalid-source-arena-id", "&c請輸入一個有效的源競技場ID！ID為 &e'{enter}' &c的競技場不存在 [clickable]view::&f&n點選檢視所有競技場對應的ID[clickable]",
            new String[][]{
                    {"view", "/dueltime arena list", "", ""}},
            "enter"),
    COMMAND_SUB_ARENA_FUNCTION_COPY_INVALID_TARGET_ARENA_ID("Command.sub.arena.function.copy-invalid-target-arena-id", "&c請輸入一個有效的目標競技場ID！ID為 &e'{enter}' &c的競技場不存在 [clickable]view::&f&n點選檢視所有競技場對應的ID[clickable]",
            new String[][]{
                    {"view", "/dueltime arena list", "", ""}},
            "enter"),
    COMMAND_SUB_ARENA_FUNCTION_COPY_DIFFERENT_TYPE("Command.sub.arena.function.copy-different-type", "&c不可以對不同型別的競技場進行該複製操作！源競技場 &e{source_arena_name}&c為 &e{source_arena_type}&c 的，而目標競技場 &e{target_arena_name}&c 為{target_arena_type}的！",
            "source_arena_name", "source_arena_type", "target_arena_name", "target_arena_type"),
    COMMAND_SUB_ARENA_FUNCTION_COPY_EMPTY_FUNCTION("Command.sub.arena.function.copy-empty-function", "&c源競技場 &e{source_arena_name}&c 尚未新增附加功能：&e{function} [clickable]view::&f&n點選檢視{source_arena_type}型別的競技場定義的所有功能ID[clickable]",
            new String[][]{
                    {"view", "/dueltime arena function type {source_arena_type_id}", "", ""}},
            "source_arena_name", "function", "source_arena_type", "source_arena_type_id"),
    COMMAND_SUB_ARENA_FUNCTION_COPY_SUCCESSFULLY("Command.sub.arena.function.copy-successfully", "&a成功將競技場 &3{source_arena}&a 的附加功能資料 &e{function} &a複製到了競技場 &b{target_arena} &a中！",
            "source_arena", "target_arena", "function"),
    COMMAND_SUB_ARENA_FUNCTION_COPY_SUCCESSFULLY_OVERWRITE("Command.sub.arena.function.copy-successfully-overwrite", "&a成功將競技場 &3{source_arena}&a 的附加功能資料 &e{function} &a複製，並覆蓋了競技場 &b{target_arena} &a原本相應的資料！",
            "source_arena", "target_arena", "function"),
    COMMAND_SUB_ARENA_FUNCTION_ADD_REPEATEDLY("Command.sub.arena.function.add-repeatedly", "&c競技場 &6{arena} &c已經包含了ID為 &e'{function_entered}' &c的附加功能了，無需重複新增",
            "arena", "function_entered"),
    COMMAND_SUB_ARENA_FUNCTION_ADD_ENTER_PROGRESS("Command.sub.arena.function.add-enter-progress", "&d嘗試為競技場 &a{arena} &d增添附加功能 &b{function}&d，請按照提示完成操作",
            "arena", "function"),
    COMMAND_SUB_ARENA_FUNCTION_ADD_SUCCESSFULLY("Command.sub.arena.function.add-successfully", "&a成功為競技場 &e{arena} &a增添附加功能 &b{function}",
            "arena", "function"),
    COMMAND_SUB_ARENA_FUNCTION_REMOVE_FAIL_NOT_EXISTS("Command.sub.arena.function.remove-fail-not-exists", "&c競技場 &e{arena} &c本來就未增添ID為 &e'{function_id}' &c的附加功能",
            "arena", "function"),
    COMMAND_SUB_ARENA_FUNCTION_REMOVE_SUCCESSFULLY("Command.sub.arena.function.remove-successfully", "&a成功為競技場 &e{arena} &a移除附加功能 &b{function}",
            "arena", "function"),
    COMMAND_SUB_ARENA_FUNCTION_RESET_FAIL_NOT_EXISTS("Command.sub.arena.function.reset-fail-not-exists", "&c競技場 &e{arena} &c本來就未增添ID為 &e'{function_id}' &c的附加功能",
            "arena", "function_id"),
    COMMAND_SUB_ARENA_FUNCTION_RESET_FAIL_NO_DATA_NEEDED("Command.sub.arena.function.reset-fail-no-data-needed", "&c競技場 &e{arena} &c的附加功能 &e'{function}' &c不需要上傳資料",
            "arena", "function"),
    COMMAND_SUB_ARENA_FUNCTION_RESET_ENTER_PROGRESS("Command.sub.arena.function.reset-enter-progress", "&d嘗試為競技場 &a{arena} &d重設附加功能 &b{function}&d 的資料，請按照提示完成操作",
            "arena", "function"),
    COMMAND_SUB_ARENA_FUNCTION_CLEAR_SUCCESSFULLY("Command.sub.arena.function.clear-successfully", "&a成功清除競技場 &e{arena} &a的所有附加功能",
            "arena"),
    COMMAND_SUB_ARENA_FUNCTION_LIST_EMPTY("Command.sub.arena.function.list-empty", "&c競技場 &e{arena} &c尚未擁有任何附加功能",
            "arena"),
    COMMAND_SUB_ARENA_FUNCTION_LIST_HEADING("Command.sub.arena.function.list-heading", "&b競技場 &f{arena} &b的附加功能如下：",
            "arena"),
    COMMAND_SUB_ARENA_FUNCTION_LIST_BODY("Command.sub.arena.function.list-body", new String[]{
            "&f&l{index}. &b{arena_function_name} &3(ID:{arena_function_id})",
            "&7描述：{arena_function_description}",
            "&7資料：{arena_function_data}"},
            "index", "arena_function_name", "arena_function_id", "arena_function_description", "arena_function_data"),
    COMMAND_SUB_ARENA_FUNCTION_LIST_ENDING("Command.sub.arena.function.list-ending", "&b共計 &3&l{number} &b種已新增的附加功能",
            "number"),
    COMMAND_SUB_ARENA_VIEW("Command.sub.arena.view", new String[]{
            "&e==============================",
            "&a名稱：&b{arena_name}",
            "&aID：&b{arena_id}",
            "&a型別：&b{arena_type}",
            "&a附加功能：&b{function_number}項[clickable]view_function::&7(點選檢視)::&f點選檢視已新增的附加功能名稱和資料[clickable]",
            "&e==============================",
    },
            new String[][]{
                    {"view_function", "/dueltime arena function list {arena_id}", "", ""}},
            "arena_name", "arena_id", "arena_type", "function_number"),
    COMMAND_SUB_ARENA_DELETE_SUCCESSFULLY("Command.sub.arena.delete-successfully", "&a成功刪除ID為 &b{arena_id} &a的競技場",
            "arena_id"),
    COMMAND_SUB_RANK_ME_DESCRIPTION("Command.sub.rank.me-description", "&b檢視自己在各個排行榜的排名"),
    COMMAND_SUB_RANK_VIEW_DESCRIPTION("Command.sub.rank.view-description", "&b檢視某個排行榜"),
    COMMAND_SUB_RANK_TYPE_DESCRIPTION("Command.sub.rank.type-description", "&b檢視所有型別的排行榜及其對應的ID"),
    COMMAND_SUB_RANK_REFRESH_DESCRIPTION("Command.sub.rank.refresh-description", "&b手動重新整理某個排行榜"),
    COMMAND_SUB_RANK_HOLOGRAM_DESCRIPTION("Command.sub.rank.hologram-description", "&b新增/刪除/移動某個排行榜對應的全息圖"),
    COMMAND_SUB_RANK_ME_HEADING("Command.sub.rank.me-heading", new String[]{
            "&b你在各個排行榜的概括資訊如下",
            "&7&m───&f&l&m────────────────────────&7&m───",
            ""
    }),
    COMMAND_SUB_RANK_ME_BODY("Command.sub.rank.me-body", "    &f{ranking_name} &a({rank}&2/{total}&a) [clickable]view_ranking::&7[點選檢視]::&f點選檢視&f{ranking_name}&f的具體資料[clickable]",
            new String[][]{
                    {"view_ranking", "/dueltime rank view {ranking_id}", "", ""}},
            "ranking_name", "rank", "total", "ranking_id"),
    COMMAND_SUB_RANK_ME_BODY_NO_DATA("Command.sub.rank.me-body-no-data", "    &f{ranking_name} &7(無記錄) [clickable]view_ranking::&7[點選檢視]::&f點選檢視&f{ranking_name}&f的具體資料[clickable]",
            new String[][]{
                    {"view_ranking", "/dueltime rank view {ranking_id}", "", ""}},
            "ranking_name", "ranking_id"),
    COMMAND_SUB_RANK_ME_ENDING("Command.sub.rank.me-ending", new String[]{
            "",
            "&7&m───&f&l&m────────────────────────&7&m───"
    }),
    COMMAND_SUB_RANK_VIEW_HEADING("Command.sub.rank.view-heading", new String[]{
            "{ranking_name}[clickable]ranking_description::&7(檢視介紹)::{ranking_description}[clickable]",
            "&7&m──&f&l&m──────────────────&7&m──",
            ""},
            new String[][]{
                    {"ranking_description", "", "", ""}},
            "ranking_name", "ranking_description"),
    COMMAND_SUB_RANK_VIEW_BODY("Command.sub.rank.view-body", "   &f&l[&7{rank}&f&l] &b{player} &f- &3{data}{extra}",
            "rank", "player", "data", "extra"),
    COMMAND_SUB_RANK_VIEW_ENDING("Command.sub.rank.view-ending", new String[]{
            "   [clickable]previous_page::&9[上一頁]::點選檢視上一頁[clickable] &9{current_page}/{total_pages} [clickable]next_page::&9[下一頁]::點選檢視下一頁[clickable]",
            "&7&m──&f&l&m──────────────────&7&m──",
            ""},
            new String[][]{
                    {"previous_page", "/dueltime rank view {ranking_id} {previous_page}", "", ""}, {"next_page", "/dueltime rank view {ranking_id} {next_page}", "", ""}},
            "previous_page", "current_page", "total_pages", "next_page", "ranking_id"),
    COMMAND_SUB_RANK_VIEW_ENDING_SHOW_ME("Command.sub.rank.view-ending-show-me", "&e你在該榜排名&6{rank}/{total} &e資料:&6{data}{extra}",
            "rank", "total", "data", "extra"),
    COMMAND_SUB_RANK_VIEW_ENDING_SHOW_ME_NO_DATA("Command.sub.rank.view-ending-show-me-no-data", "&e你在該排行榜中無資料記錄"),
    COMMAND_SUB_RANK_INVALID_RANKING_TYPE_ID("Command.sub.rank.view-invalid-ranking-type-id", "&c型別ID為 &e'{enter}' &c的排行榜不存在 [clickable]view::&f&n點選檢視所有型別ID[clickable]",
            new String[][]{
                    {"view", "/dueltime rank type", "", ""}},
            "enter"),
    COMMAND_SUB_RANK_VIEW_EMPTY("Command.sub.rank.view-empty", "&c排行榜 &e{ranking}&c 暫時沒有資料",
            "ranking"),
    COMMAND_SUB_RANK_VIEW_INVALID_RANKING_PAGE("Command.sub.rank.view-invalid-ranking-page", "&c請輸入有效的頁碼，該排行榜的總頁數為&6{total_pages}&c頁",
            "total_pages"),
    COMMAND_SUB_RANK_TYPE_HEADING("Command.sub.rank.type-heading", "&b排行榜型別如下："),
    COMMAND_SUB_RANK_TYPE_BODY("Command.sub.rank.type-body", new String[]{
            "&f&l{index}. &b{type_name} &3(ID:{type_id})",
            "&7描述:&f{description}"},
            "index", "type_name", "type_id", "description"),
    COMMAND_SUB_RANK_TYPE_ENDING("Command.sub.rank.type-ending", "&b共計 &3&l{number} &b種排行榜",
            "number"),
    COMMAND_SUB_RANK_REFRESH_INTERNAL_SUCCESSFULLY("Command.sub.rank.refresh-internal-successfully", "&a成功手動重新整理外掛內建排行榜：&f{ranking_name}&7(ID:{ranking_id})",
            "ranking_name", "ranking_id"),
    COMMAND_SUB_RANK_HOLOGRAM_DISABLED("Command.sub.rank.hologram-disabled", "&c全息模組已關閉或未裝載受本外掛支援的全息外掛，暫時無法使用此功能"),
    COMMAND_SUB_RANK_HOLOGRAM_ADD_FAIL_ALREADY_EXISTS("Command.sub.rank.hologram-add-fail-already-exists", "&e{ranking} &c已經被新增了全息圖，位置：&e{location}",
            "ranking", "location"),
    COMMAND_SUB_RANK_HOLOGRAM_ADD_SUCCESSFULLY("Command.sub.rank.hologram-add-successfully", "&a成功為排行榜 &b{ranking} &a新增全息圖，位置：&e{location}",
            "ranking", "location"),
    COMMAND_SUB_RANK_HOLOGRAM_DELETE_FAIL_NOT_EXISTS("Command.sub.rank.hologram-delete-fail-not-exists", "&c無效刪除，&e{ranking} &c尚未被新增全息圖",
            "ranking"),
    COMMAND_SUB_RANK_HOLOGRAM_DELETE_SUCCESSFULLY("Command.sub.rank.hologram-delete-successfully", "&a成功為排行榜 &b{ranking} &a刪除全息圖，位置：&e{location}",
            "ranking", "location"),
    COMMAND_SUB_RANK_HOLOGRAM_MOVE_FAIL_NOT_EXISTS("Command.sub.rank.hologram-move-fail-not-exists", "&c無效移動，&e{ranking} &c尚未被新增全息圖",
            "ranking"),
    COMMAND_SUB_RANK_HOLOGRAM_MOVE_SUCCESSFULLY("Command.sub.rank.hologram-move-successfully", "&a成功為排行榜 &b{ranking} &a移動全息圖，新的位置：&e{location}",
            "ranking", "location"),
    COMMAND_SUB_QUIT_NOT_IN_ARENA("Command.sub.quit.not-in-arena", "&c只有在競技場比賽時才能使用這個指令"),
    COMMAND_SUB_SPECTATE_FAIL_ARENA_NOT_EXISTS("Command.sub.spectate.fail-arena-not-exists", "&c競技場 &e'{arena}' &c不存在，無法觀看",
            "arena"),
    COMMAND_SUB_SPECTATE_FAIL_ARENA_DISABLED("Command.sub.spectate.fail-arena-disabled", "&c競技場 &e{arena} &c處於停用狀態，無法觀看",
            "arena"),
    COMMAND_SUB_SPECTATE_FAIL_ARENA_NO_GAMES("Command.sub.spectate.fail-arena-no-games", "&c競技場 &e{arena} &c現在沒有正在進行的比賽，無法觀看",
            "arena"),
    COMMAND_SUB_QUIT_SUCCESSFULLY("Command.sub.quit.successfully", "&b你退出了競技場 &e{arena} &b上的比賽",
            "arena"),
    RANKING_HOLOGRAM_HEADING("Ranking.hologram.heading", new String[]{
            "{ranking_name}",
            "{ranking_description}"},
            "ranking_name", "ranking_description"),
    RANKING_HOLOGRAM_BODY("Ranking.hologram.body", "&b&lTOP{rank}.&b{player} &f&l- &3{data}{extra}",
            "rank", "player", "data", "extra"),
    RANKING_HOLOGRAM_ENDING("Ranking.hologram.ending", new String[]{
            "---"},
            "ranking_name", "ranking_description"),
    RANKING_TYPE_CLASSIC_WINS_NAME("Ranking.type.classic-wins.name", "&b經典模式勝場榜"),
    RANKING_TYPE_CLASSIC_WINS_DESCRIPTION("Ranking.type.classic-wins.description", "&7在經典模式中贏下的場次越多排名越高"),
    RANKING_TYPE_CLASSIC_WIN_RATE_NAME("Ranking.type.classic-win-rate.name", "&d經典模式勝率榜"),
    RANKING_TYPE_CLASSIC_WIN_RATE_DESCRIPTION("Ranking.type.classic-win-rate.description", "&7在經典模式中的勝率越高排名越靠前"),
    RANKING_TYPE_EXP_NAME("Ranking.type.exp.name", "&a經驗榜"),
    RANKING_TYPE_EXP_DESCRIPTION("Ranking.type.exp.description", "&7經驗總額越多排名越靠前"),
    RANKING_TOTAL_GAME_NUMBER_TYPE_NAME("Ranking.type.total-game-number.name", "&e全模式場數榜"),
    RANKING_TOTAL_GAME_NUMBER_TYPE_DESCRIPTION("Ranking.type.total-game-number.description", "&7即參與經典模式及DT任意附屬外掛的任意模式的次數"),
    RANKING_TOTAL_GAME_TIME_TYPE_NAME("Ranking.type.total-game-time.name", "&6全模式時長榜"),
    RANKING_TOTAL_GAME_TIME_TYPE_DESCRIPTION("Ranking.type.total-game-time.description", "&7即參與經典模式及DT任意附屬外掛的任意模式的時長，按秒數記"),
    RANKING_CLASSIC_GAME_NUMBER_TYPE_NAME("Ranking.type.classic-game-number.name", "&e經典模式場數榜"),
    RANKING_CLASSIC_GAME_NUMBER_TYPE_DESCRIPTION("Ranking.type.classic-game-number.description", "&7即參與經典模式的次數"),
    RANKING_CLASSIC_GAME_TIME_TYPE_NAME("Ranking.type.classic-game-time.name", "&6經典模式時長榜"),
    RANKING_CLASSIC_GAME_TIME_TYPE_DESCRIPTION("Ranking.type.classic-game-time.description", "&7即參與經典模式的時長，按秒數記"),
    ;


    private final String key;
    private final String[] defaultMessage;
    private final String[] variable;
    private final String[][] clickableSettingsList;

    /**
     * 構造單條提示語
     *
     * @param key            對應的配置檔案key名
     * @param defaultMessage 預設單條提示語
     * @param variable       變數（可選）
     */
    Msg(String key, String defaultMessage, String... variable) {
        this.key = key;
        this.defaultMessage = new String[]{defaultMessage};
        this.variable = variable;
        this.clickableSettingsList = null;
    }

    /**
     * 構造單條含有可點選文字的提示語
     *
     * @param clickableSettingsList 可點選文字的內定設定資訊，依次為：佔位符名、執行的指令、建議的指令、開啟的URL
     */
    Msg(String key, String defaultMessage, String[][] clickableSettingsList, String... variable) {
        this.key = key;
        this.defaultMessage = new String[]{defaultMessage};
        this.variable = variable;
        this.clickableSettingsList = clickableSettingsList;
    }

    /**
     * 構造多條提示語
     *
     * @param key             對應的配置檔案key名
     * @param defaultMessages 預設多條提示語
     * @param variable        變數（可選）
     */
    Msg(String key, String[] defaultMessages, String... variable) {
        this.key = key;
        this.defaultMessage = defaultMessages;
        this.variable = variable;
        this.clickableSettingsList = null;
    }

    /**
     * 構造多條含有可點選文字的提示語
     *
     * @param clickableSettingsList 可點選文字的內定設定資訊，依次為：佔位符名、執行的指令、建議的指令、開啟的URL
     */
    Msg(String key, String[] defaultMessages, String[][] clickableSettingsList, String... variable) {
        this.key = key;
        this.defaultMessage = defaultMessages;
        this.variable = variable;
        this.clickableSettingsList = clickableSettingsList;
    }

    public String getKey() {
        return key;
    }

    public String getDefaultMessage() {
        return defaultMessage[0];
    }

    public String[] getDefaultMessages() {
        return defaultMessage;
    }

    public String[] getVariable() {
        return variable;
    }

    public String[][] getClickableSettingsList() {
        return clickableSettingsList;
    }
}
